### ISSUE TITLE
看了代码，作者类库实现的想法不错，我提供一点我自己的想法吧

### ISSUE THREAD

**Issue by LuckyJayce** [drakeet/MultiType#10]
看了代码，实现的想法不错，  
根据数据类型创建对应的ItemViewProviderd，ItemViewProviderd对ViewHolder执行了onCreateView，onBindView，这使得ViewHolder从Adapter抽离出来给多种Adapter复用.  

不过感觉框架使用时代码还是比较多，  
我说点自己的想法吧。  

定义一个ItemViewProvider工厂接口，根据数据类型创建对应的ItemViewProvider，  
代替之前的ItemTypePool.register.因为ItemTypePool.register是全局注册的，而ItemViewProviderFactory可以是使用时切换，也可以复用。

```
 public interface ItemViewProviderFactory {
         ItemViewProvider made(Object data);
  }
```

TypeItemsAdapter构
定义一个ItemViewProvider工厂接口，根据数据类型创建对应的ItemViewProvider，  
代替之前的ItemTypePool.register.因为ItemTypePool.register是全局注册的，而ItemViewProviderFactory可以是使用时切换，也可以复用。

```
 public interface ItemViewProviderFactory {
         ItemViewProvider made(Object data);
  }
```

TypeItemsAdapter构造函数：datas 数据列表，使用者自己实现的ChatItemViewProviderFactory的ItemViewProvider工厂. 

```
recyclerView.setAdapter(new TypeItemsAdapter(datas, new ChatItemViewProviderFactory()));
```

**Comment by drakeet** [comment]
是可以做局部类型池，但之所以使用全局的原因出于两点考虑：

一，整个应用一般类型不会太多，很难很难超过一百种，而且 provider 都是轻薄的类对象，存储的内存占用可以忽略，或者说不必担心；

二，全局能够使得注册归于一个统一的地方，更加直观和便于管理。建议在 Application 初始化便进行预先注册全部类型。

综上，目前仍然偏向全局。

**Comment by drakeet** [comment]
另外，你的表述略微有点凌乱，暂且 closed，如若能够修改得更清晰，且后续讨论，再 reopen.

**Comment by drakeet** [comment]
或许，局部类型池可以作为 optional 参数，这倒可以接受。

**Comment by LuckyJayce** [comment]
我写了个demo，已经发到你gmail邮箱上了

**Comment by drakeet** [comment]
晚上我会改为
onCreateViewHolder，但暂时还是坚持不支持局部类型池，因为我不想让类型分散注册，这是没必要的，而且会分散各地，若可选也会使用户疑惑“到底要还是不要？”。非常感谢你的贡献和让这个项目越来越好！
LuckyJayce notifications@github.com于2016年8月5日 周五19:28写道：
