### ISSUE TITLE
IndexOutOfBoundsException happened when getLaidBinderByViewHolder

### ISSUE THREAD

**Issue by plusend** [drakeet/MultiType#104]
![multitype](https://cloud.githubusercontent.com/assets/10849674/24503129/56efade4-1583-11e7-8b54-d032a8bf1535.png)

在我看了 commit [e2f7ec3f](https://github.com/drakeet/MultiType/commit/e2f7ec3f35b96461185f2e89b369b1a50faa3d37) 之后我更新了 beta3 版本，没有这个问题了。
我尝试找出复现路径，大概是在我在列表的下方超过1屏的地方，remove 上一屏的 item 时会出现这个问题。

之前也有个类似的问题，复现路径我记不清了，在 commit [689b72a5](https://github.com/drakeet/MultiType/commit/689b72a552040bfe9fa2f7407a5f1672aa25b97a) 之中进行了修改。

我从 beta1 改动到了 beta2，又到 beta3。
想问下 2.5.0 是还不稳定么？我需要退回 2.4 的版本么？（我没试 2.4.0 的版本有没有这些问题。）

**Comment by drakeet** [comment]
感谢你的测试与反馈，你的问题已经在 beta3 修复了，并且 1.5.0 beta3 已经相对稳定许多了，目前无人再反馈问题，再过一两周观察时间可能就改为正式版了。在此期间，如果你期望稳定性保证的话，可以使用最新稳定版 2.4.3.🌞

**Comment by drakeet** [comment]
另外 1.5.0-beta3 也补足覆盖了一些测试用例且都测试通过，因此基本上可以说接近稳定正式版了。

**Comment by plusend** [comment]
可能要内置到手机 ROM 里的，所以想稳定一些。
2.4 和 2.5 改了一些类名（Provider vs Binder），改起来有点麻烦，又担心这些问题之前的版本也有，就没改回 2.4。就继续用着 beta3 吧。😀
