### ISSUE TITLE
请教一下大神关于onBindViewHolder(holder, item, payloads)的一些问题

### ISSUE THREAD

**Issue by woniu0936** [drakeet/MultiType#110]
我有些不理解payloads为什么是一个List而不是一个Object，甚至为什么不是itemView对应的那个bean？官方的RecyclerView.Adapter这么做是从哪方面考虑的？

**Comment by drakeet** [comment]
The `payloads` means the contents of a bean, so it should be Objects. I recommend using `Pair` or `FieldEntry` to carry the payload item. More you should refer to the official documentation:

```java
* The payloads parameter is a merge list from {@link #notifyItemChanged(int, Object)} or
* {@link #notifyItemRangeChanged(int, int, Object)}.  If the payloads list is not empty,
* the ViewHolder is currently bound to old data and Adapter may run an efficient partial
* update using the payload info.  If the payload is empty,  Adapter must run a full bind.
* Adapter should not assume that the payload passed in notify methods will be received by
* onBindViewHolder().  For example when the view is not attached to the screen, the
* payload in notifyItemChange() will be simply dropped.
```

**Comment by woniu0936** [comment]
实在不好意思，英语实在太差，不是很能理解您的意思。能不能用汉语/(ㄒoㄒ)/~~，不胜感激

**Comment by drakeet** [comment]
@woniu0936 简单翻译：`payloads` 指的是 bean 的局部内容，一个 bean 的内容有很多而且类型不定，所以它是个 Object list.

**Comment by woniu0936** [comment]
那您 I recommend using Pair or FliedEntry to carry the payload item这句话里面的Pair和FliedEntry指的是？？

**Comment by drakeet** [comment]
It means some key-value models.

**Comment by woniu0936** [comment]
的确，局部刷新的话，key-value model更合适。再次感谢！
