### ISSUE TITLE
一对多情况下，onBindContentViewHolder 里获取 position 都是-1

### ISSUE THREAD

**Issue by Curzibn** [drakeet/MultiType#111]
3.x分支demo中 weibo 例子的两个 viewbinder 都有这种情况
![image](https://cloud.githubusercontent.com/assets/4538051/24790861/83922804-1baa-11e7-9cba-eba91d3573ad.png)

**Comment by drakeet** [comment]
@Curzibn 你搞错了吧？你观察的是 ViewHolder 内部的私有变量，这些是不保证的，取决于 RV 的机制。你需要使用 `holder.getAdapterPosition()`，如果它是 -1，那才证明有问题。

另外，请说明下你 close 这个 issue 的原因。

**Comment by Curzibn** [comment]
这里调用`holder.getAdapterPosition()`也会是-1的。
这里我通过抽象方法把`position`传递进去就行了。
`    protected abstract void onBindContentViewHolder(
        @NonNull SubViewHolder holder, @NonNull Content content, int position);`

**Comment by drakeet** [comment]
你看官方文档，position 是不提倡使用的，你这样做容易和官方"不提倡"混淆。

官方对于 onBindViewHolder(VH holder, int position) 的文档，position 不会实时刷新，它的值很可能不正确：
```java
* Note that unlike {@link android.widget.ListView}, RecyclerView will not call this method
* again if the position of the item changes in the data set unless the item itself is
* invalidated or the new position cannot be determined. For this reason, you should only
* use the <code>position</code> parameter while acquiring the related data item inside
* this method and should not keep a copy of it. If you need the position of an item later
* on (e.g. in a click listener), use {@link ViewHolder#getAdapterPosition()} which will
* have the updated adapter position.
```

**Comment by drakeet** [comment]
如果 `holder.getAdapterPosition()` 也返回 -1，那么说明当前一对多方案有问题，可能需要推翻，请谨慎选择使用。

**Comment by drakeet** [comment]
或许是因为 samples 中关于一对多的示例 models 没有严格重写 equals 方法导致的问题，晚上验证并测试下。

**Comment by drakeet** [comment]
如果是这样的话，一对多的 model / Java bean 类得提示必须严格覆写 equals 方法 🤔

**Comment by drakeet** [comment]
@Curzibn 我测试了一番都正常，才发觉你指的是 `WeiboFrameBinder` 的子类 binders，这些子类调用 `holder.getAdapterPosition()` 当然都是 -1 了，因为这些 holder 不是完整的 RV holder，它们只用于提供 sub-content-view，因此我原先设计的时候，没有传递 position 给它们，如若需要，完全可以传递给它们。对于普通一对多场景，在 onBindViewHolder 都能正常获取到 position，因此这不是 bug，可以说设计如此，或者说属于 weibo sample 的小缺陷（很容易修正）。

另外，这个问题应该和 3.0 无关，3.0 之前应该也是这样的。

**Comment by drakeet** [comment]
由于 RV ViewHolder 很多方法为 final 无法覆写，于是我使用了 parent 代理来解决这个问题，新的 ContentHolder：

```java
public class ContentHolder {

    WeiboFrameBinder.FrameHolder frameHolder;

    public final View itemView;


    public ContentHolder(@NonNull final View itemView) {
        this.itemView = itemView;
    }

    @NonNull
    public WeiboFrameBinder.FrameHolder getParent() {
        return frameHolder;
    }


    public final int getAdapterPosition() {
        return getParent().getAdapterPosition();
    }


    public final int getLayoutPosition() {
        return getParent().getLayoutPosition();
    }


    public final int getOldPosition() {
        return getParent().getOldPosition();
    }


    public final boolean isRecyclable() {
        return getParent().isRecyclable();
    }


    public final void setIsRecyclable(boolean recyclable) {
        getParent().setIsRecyclable(recyclable);
    }
}
```

**Comment by drakeet** [comment]
@Curzibn 现在可以无感知使用了，基于 MultiType 3.0.

![image](https://cloud.githubusercontent.com/assets/5214214/24801838/56dbed12-1bd8-11e7-91d8-fc3c535c2cf4.png)

**Comment by drakeet** [comment]
晚上抽空解决了这个问题，这个问题其实不属于 MultiType 类库的问题而是示例代码本身设计的问题，已经修正了。而且经过更多测试用例测试，总的来说目前 MultiType 3.0 一对多实现方案仍然是稳定和可靠的。
