### ISSUE TITLE
alibaba的vlayout开源项目与你的MultiType比较有什么优缺点吗？

### ISSUE THREAD

**Issue by renyanxu2000** [drakeet/MultiType#114]

**Comment by drakeet** [comment]
MultiType 无意于与其他项目对比，另外我不熟悉 vlayout 的优缺点，但既然你问了，我就去看了看 vlayout. 
简单来说，vlayout 支持的 MultiType 几乎全都支持，但差别还是有的，MultiType 简单清晰、直观、灵活，源代码和示例代码可谓一丝不苟。vlayout 看起来也很强大，切入面不同，在瀑布流混合布局方面有更好的支持，但相对来说 vlayout 代码源代码和示例代码较为凌乱、复杂、使用起来也不是很方便和直观。

**Comment by JakeWoki** [comment]
不是两个不同概念的东西吗？vlayout是对LayoutManager的扩展，主要是对item的布局。MultiType是对RecyclerView.Adapter的封装。其实我觉得封装成[AdapterDelegates](https://github.com/sockeqwe/AdapterDelegates)这种形式更好
