### ISSUE TITLE
Item 无法触发点击事件

### ISSUE THREAD

**Issue by chowaikong** [drakeet/MultiType#116]
从 2.4.3 版本升级到 2.5.0 后我发现原本设置的点击事件接口失效了。  
接口代码： 
```java
interface OnItemClickListener<in T> {
  fun onItemClick(itemView: View, position: Int, value: T)
}
```
加载数据：
```java
(0..10).forEach {
  mItems.add(Order())
}
mAdapter.notifyItemRangeInserted(0, items.size)
```
在 ItemViewBinder 中设置的点击：
```java
itemView.setOnClickListener {
  itemListener.onItemClick(it, holder.adapterPosition, value)
}
```
加载更多数据的代码：
```java
LoadMoreWrapper.with(mAdapter)
        .setLoadMoreEnabled(true)
        .setListener {
          (0..20).forEach {
            mItems.add(Order())
          }
          list.postDelayed({
          mAdapter.notifyItemRangeInserted(previousPosition, 21)
          }, 1000)
          previousPosition = mItems.size
        }
        .into(list)
```
我纳闷的是，同一份代码，两个版本的效果不一样，虽然 2.5.0 版本的改动不大。另外就是我同时在使用一个 RecyclerView 加载更多数据的第三方库 [LoadMoreWrapper](https://github.com/nukc/LoadMoreWrapper) ，如果在使用 2.5.0 版本的代码去掉加载更多又是正常的响应点击事件，不去掉的话在 2.5.0 版本是失效的，更加困惑我的是，我已经搞不清是谁的代码出问题了，我尝试把 [LoadMoreWrapper](https://github.com/nukc/LoadMoreWrapper) 引入到你的 sample 里面的 communicate_with_binder，又是正常的响应点击事件的。

**Comment by drakeet** [comment]
很明显，是 LoadMoreWrapper 这个库的问题，我看了它的源码，它这么做侵入性太强了，它在 `onBindViewHolder(RecyclerView.ViewHolder holder, int position)` 对数据进行侵入和绑定，而 MultiType 2.5 使用了 `onBindViewHolder(VH holder, int position, List<Object> payloads)` 来绑定数据，因此照它这么侵入，肯定出问题，因此 binder 的 `onBindViewHolder` 并不会回调。

**Comment by drakeet** [comment]
LoadMoreWrapper 的思路就是错的，如果你需要 LoadMore 功能，可以参考我的 rebase-android 的 LoadMoreDelete 代码，LoadMoreDelete 提供了高度解耦和低侵入的方式实现了灵活的加载更多功能。

不过，为了避免后续有人再陷入你这个问题之中，我们可能需要考虑在 MultiType 的 `onBindViewHolder(RecyclerView.ViewHolder holder, int position)`  方法中默认抛出异常来提示禁止直接调用。

附：
LoadMoreDelete (GPL v3 协议): https://github.com/drakeet/rebase-android/blob/master/app/src/main/java/com/drakeet/rebase/tool/LoadMoreDelegate.java

**Comment by chowaikong** [comment]
是不是可以认为 LoadMoreWrapper 覆盖了原来的 `onBindViewHolder `已经绑定的数据？

**Comment by drakeet** [comment]
鉴于这个问题实属你使用的第三方库（LoadMoreWrapper）的问题，暂且关闭。你可以过去找 LoadMoreWrapper 的作者，建议他不要使用这种方法，或者修改调用  `onBindViewHolder(VH holder, int position, List<Object> payloads) `，如果他了解 RecyclerView 的源码的话，就会知道 `onBindViewHolder(VH holder, int position, List<Object> payloads) ` 默认实际上会调用 `onBindViewHolder(RecyclerView.ViewHolder holder, int position)`，因此调用 payloads 方法实际上是更可靠而且准确的。

**Comment by drakeet** [comment]
它写死了间接调用外来 adapter 两参数 onBind 方法，但实际上，这是不可靠的做法，payloads 方法一旦被覆写，一切就不是如它所料了。这不管对普通 RV Adapter 还是 MultiTypeAdapter 都是一样的结果：

https://github.com/nukc/LoadMoreWrapper/blob/master/loadmorewrapper/src/main/java/com/github/nukc/LoadMoreWrapper/LoadMoreAdapter.java#L109

**Comment by chowaikong** [comment]
是的，我修改他的代码，实现了 `onBindViewHolder(RecyclerView.ViewHolder holder, int position,
        List<Object> payloads)` 就正常了。
