### ISSUE TITLE
Think about remove MultiTypeAdapter#items:List<?> and add the ability to impl custom Collection ?

### ISSUE THREAD

**Issue by xyzxqs** [drakeet/MultiType#124]

**Comment by drakeet** [comment]
It is able to use custom Collection originally. MultiTypeAdapter accepts `List<?> items` not `Items`. `Items` is just a class for convenient.

**Comment by xyzxqs** [comment]
I know that. I mean custom collection like SortedList.

**Comment by drakeet** [comment]
No, `List` is already a very abstract container. If you want to use some list which is not extending `List`, you should create a full and real List wrapper or delegate. And `SortedList` just extends `Object`, it is unusable and unpredictable.

**Comment by drakeet** [comment]
`List` is an interface. If you want to use custom collections or objects, you should implement the interface, not break it.

**Comment by woniu0936** [comment]
`package android.support.v7.util;

import java.lang.reflect.Array;
import java.util.Arrays;
import java.util.Collection;
import java.util.Comparator;

/**
 * A Sorted list implementation that can keep items in order and also notify for changes in the
 * list
 * such that it can be bound to a {@link android.support.v7.widget.RecyclerView.Adapter
 * RecyclerView.Adapter}.
 * <p>
 * It keeps items ordered using the {@link Callback#compare(Object, Object)} method and uses
 * binary search to retrieve items. If the sorting criteria of your items may change, make sure you
 * call appropriate methods while editing them to avoid data inconsistencies.
 * <p>
 * You can control the order of items and change notifications via the {@link Callback} parameter.
 */
@SuppressWarnings("unchecked")
public class SortedList<T> {...}`
