### ISSUE TITLE
MultiType + CoordinatorLayout 混合使用出现下穿的情况

### ISSUE THREAD

**Issue by KrisLain** [drakeet/MultiType#125]
AppBarLayout 布局中 是轮播图 + toolbar

RecyclerView向上滑动的时候 会穿过 轮播图 从底部划上去。 这样轮播图也就没有收缩。体验有些不友好，我也不知道是什么问题。。。

**Comment by drakeet** [comment]
这是 CoordinatorLayout 的问题。即使你不使用 MultiType 而是使用原生 RecyclerView 也一样会这样。**MultiType 不会去影响你的 Views 内容，它是很轻薄的一层，只负责类型分发。**

如果你要问 CoordinatorLayout 为什么会这样，我倒是可以告诉你：你可能没有设置正确的 behavior.

另外，你既然使用了 MultiType，应该把轮播图置于 RecyclerView 内部（我猜你目前是与 RecyclerView 上下线性关系）。

**Comment by drakeet** [comment]
P.S. 无关 MultiType 本身的问题，请不要在此讨论，因此关闭这个 issue，以免打扰到其他订阅本项目的朋友。如若你实在无法自行解决你的问题，可以给我发邮件，但在发送之前，**你得详细描述你的需求、你所遇到的问题、你自己为此付出的努力和思考，并贴上尽可能详细的相关代码**，谢谢。
