### ISSUE TITLE
In the sample, BiliBili page nested RecyclerView sometimes not rebind view after notifyDataSetChanged

### ISSUE THREAD

**Issue by dongorigin** [drakeet/MultiType#129]
Nested RecyclerView sometimes not rebind view after notifyDataSetChanged.  
[I prepared a Sample](https://github.com/dongorigin/NestedRecyclerViewSample), the sample use original adapter, MultiTypeAdapter also has the same issue

![reproduce_setps](https://cloud.githubusercontent.com/assets/6520963/25582497/2ac1dc82-2ec0-11e7-8052-4b2de6c475af.gif)

### Steps to reproduce 
1. launch activity
2. scroll down to item:10, close to item:11
3. scroll up to item:1
4. item:1's child item display error.

### Frequency 
100%

### Expected output 
Item:1's child item 1 and 2 display "row:1 col0" and "row:1 col1".  
Nested child RecyclerView's adapter correctly call onBindViewHolder after notifyDataSetChanged.

### Current output 
Item:1's child item 1 and 2 display "row:11 col0" and "row:11 col1".  
Nested child RecyclerView's adapter not call onBindViewHolder after notifyDataSetChanged, causing item to display error.

### Environment
- device: Nexus 5  
- os: Android 6.0.1  
- ide: Android Studio 2.3.1  
- dependencies: support 25.3.1

**Comment by dongorigin** [comment]
I have tested several support library builds, it appears that the problem only happens after build 25.1.0 (included).
So I think this is related to prefetching. After the prefetching is closed (layoutManager.setItemPrefetchEnabled(false)), the problem disappears.

**Comment by dongorigin** [comment]
The question has been submitted to AOSP  
https://issuetracker.google.com/issues/37139449

**Comment by drakeet** [comment]
I am very busy recently. Thank you for your detailed report and feedback!
