### ISSUE TITLE
这种布局是否有更好的写法

### ISSUE THREAD

**Issue by ddiptg** [drakeet/MultiType#130]
布局大体如下, 现在的思路是写4种Provider, 分别对应的 组, 表头, 子item, 备注.  现在是否有更好的写法

![item](https://cloud.githubusercontent.com/assets/17867028/25603408/fe49c2aa-2f2d-11e7-8df4-8757ac2acfbb.png)

**Comment by drakeet** [comment]
你的思路是不错的，不用担心。尽可能扁平化和模块化将给后期带来很大的灵活度和便利。

**Comment by drakeet** [comment]
或者，你可以把组内容用一个子 RV 承载，考虑 wrap content.

**Comment by ddiptg** [comment]
@drakeet 写4个Provider 会有一种分裂的感觉. 嵌套RecyclerView担心有性能的影响.

**Comment by hyfink** [comment]
@drakeet 对于这种情况，我也想的是将[数据扁平化处理](https://github.com/drakeet/Effective-MultiType/blob/master/README.md#%E6%95%B0%E6%8D%AE%E6%89%81%E5%B9%B3%E5%8C%96%E5%A4%84%E7%90%86)。此外我想请教一个问题：
数据这样处理之后，在获取子Item的数据Bean时，如何优雅的获取其所属组的数据Bean？因为子Item与组Item是从属关系，数据上也会有依赖。

**Comment by AlexMa1755** [comment]
> 或者，你可以把组内容用一个子 RV 承载，考虑 wrap content.
子recyclerview这种情况下会一次性bind所有的viewholder,. 假设子RV的vh都是图片, 容易导致性能问题.
