### ISSUE TITLE
不显示

### ISSUE THREAD

**Issue by vonions** [drakeet/MultiType#132]
请问3.0的为什么我的什么都不显示，就是一个空的界面，我把demo的代码全部拷贝下来也是一样的，什么都不显示

**Comment by drakeet** [comment]
无法复现，请提供问题相关的代码，包括其 Java 代码和布局文件代码，否则没有人知道你代码怎么写或怎么回事。

**Comment by drakeet** [comment]
请问你解决了吗？为什么 close?

**Comment by vonions** [comment]
我解决了，一个低级错误，所以不好意思问了就关了

**Comment by vonions** [comment]
谢谢

**Comment by drakeet** [comment]
明白了，解决了就好: )
