### ISSUE TITLE
你好，请问当recycleview 中再嵌套一个水平的recycleview 时候，register应该怎样把数据注入进去额？

### ISSUE THREAD

**Issue by nuoxi1993** [drakeet/MultiType#133]
现在需求是，垂直的recycleview 中需要一个水平的recycleview 来水平显示图片列表

其中外层的recycleview 实现的是四种Provider类型：用户信息，图片，视频，底部信息
这是数据模型：

    public static class ItemsBean {
        private RecorderInfoBean recorder_info;

        private List<PicInfoBean> pics;

        private FromBean from;

        private VideoBean video;}

谢谢大神。

**Comment by drakeet** [comment]
请参考：

https://github.com/drakeet/MultiType/blob/3.x/sample/src/main/java/me/drakeet/multitype/sample/bilibili/BilibiliActivity.java#L115

https://github.com/drakeet/MultiType/blob/3.x/sample/src/main/java/me/drakeet/multitype/sample/bilibili/PostList.java

https://github.com/drakeet/MultiType/blob/3.x/sample/src/main/java/me/drakeet/multitype/sample/bilibili/HorizontalPostsViewBinder.java

**Comment by nuoxi1993** [comment]
@drakeet  谢谢啦。知道怎么用啦

**Comment by nuoxi1993** [comment]
@drakeet demo里面好像没有item 移除处理的相关事例额，一个item 是由几个Provider组成的，当其中一个Provider 有个点赞，怎样获取这个Provider 中的bean 实现数组更新额？还有假如item 的点击事件 是要每个Provider 都设置相同的点击事件实现跳转么

**Comment by drakeet** [comment]
`Binder`(Provider, 3.0 改名为 Binder) `onBindViewHolder` 方法可以拿到 view、data，另外，也可以通过 `getAdapter()` 方法获得与之关联的 `MultiTypeAdapter`. `MultiTypeAdapter` 可以获取到整个列表所有 `items`、可以 `notify` UI 刷新（或者直接使用 `holder` 修改 view）。

**Comment by nuoxi1993** [comment]
不好意思，可能是我没有表达清楚。
1.一个item 是由几个Provider组成，要实现item 的点击跳转到详情页，是需要在每个Provider 的holder设置相同的跳转详情来实现么？
2.假如其中一个Provider 中有一个点赞数，点击这个item 进入详情页的点赞，再返回到这个列表页，这个item上的点赞数+1，multiTypeAdapter中获取到的是所有的item，那么怎么来更新这个Provider的数据呢

**Comment by drakeet** [comment]
> Binder(Provider, 3.0 改名为 Binder) onBindViewHolder 方法可以拿到 view、data

Q: 那么怎么来更新这个Provider的数据呢？
A: 直接修改 onBindViewHolder data/item 就行了，它就是你要修改的那个对象。

**Comment by drakeet** [comment]
你需要在回来时，修改 items 中相关的 item 数据对象，然后调用 adapter.notifyDataSetChanged();
nuoxi1993 <notifications@github.com>于2017年5月11日 周四17:54写道：

**Comment by nuoxi1993** [comment]
@drakeet  
1。是的哦，现在就是 我一个item 是由几个binder组成，比如一个item 有三个binder 然后需要修改这个binder 对应的数据对象，但是multiTypeAdapter拿到的是所有的item，怎么获取当前的binder 的数据对象额？
2.还有一个问题，我从2.x升级到3.0 以前的GlobalMultiTypePool 全局的这个 现在应该怎么设置额

**Comment by drakeet** [comment]
GlobalMultiTypePool 已经删除。关于 3.0 的更新内容和 GlobalMultiTypePool 删除的原因请见 [wiki](https://github.com/drakeet/MultiType/wiki/Android-%E5%A4%8D%E6%9D%82%E7%9A%84%E5%88%97%E8%A1%A8%E8%A7%86%E5%9B%BE%E6%96%B0%E5%86%99%E6%B3%95).

[wiki · 使用 全局类型池](https://github.com/drakeet/MultiType/wiki/Android-MultiType-3.0#%E4%BD%BF%E7%94%A8-%E5%85%A8%E5%B1%80%E7%B1%BB%E5%9E%8B%E6%B1%A0)

**Comment by drakeet** [comment]
关于第一点，你的语言表述未能让我明白。

**Comment by nuoxi1993** [comment]
@drakeet 当需要移除一个item 时候， multiTypeAdapter.getItems().remove(position); 移除的是item中的一个binder，怎样移除整个item 呢
