### ISSUE TITLE
对于在 RecyclerView 中使用 RadioButton 或者 CheckBox 之类的情况

### ISSUE THREAD

**Issue by PPTing** [drakeet/MultiType#139]
在 Recyclerview 中使用 RadioButton 或者 CheckBox 之类的实现列表的单选或者一些其他的需求，一般都会使用在数据源里增加一个属性去作为 RadioButton 或者 CheckBox 是否选中的标志，但我在使用这个库的过程中，因为 **XXXViewProvider** 中的 **onBindViewHolder((@NonNull V holder, @NonNull T t))** 方法只能取到当前的 item 的数据，如果我需要在点击当前的 item 时将其 RadioButton 或者 Checkbox 选中，并将其他的 item 置为未选中，我需要将数据源遍历，但在 **XXXViewProvider** 中无法实现这个需求，我每次都得写一个 interface listener 将点击事件 传递出去处理数据源然后再进行 **notifyDataSetChanged()** ，不知道您是否有考虑过这个问题或者有其他更为优雅的解决方案呢？

**Comment by drakeet** [comment]
ItemViewBinder（Provider）内部可以通过 getAdapter().getItems() 获取到所有 items.

**Comment by drakeet** [comment]
以上是最简单的做法。ItemViewProvider 或 ItemViewBinder 本身都提供了获取 adapter 或 items 的途径。
你的做法也可行。但考虑到内聚性，你不应该将该逻辑交于外界处理。
另外，你也可以在 binder 初始化时，将 items 引用传递给它，虽然没有必要。

注：ItemViewProvider 在 2.5 和 3.0 版本改名为 ItemViewBinder.

**Comment by drakeet** [comment]
Change Log

https://github.com/drakeet/MultiType/releases

**Comment by PPTing** [comment]
@drakeet 确实我也觉得用 interface 传递出去这样写很气该，但我没找到 getItems 的方法，原来后面的版本里增加了这个 ** MultiTypeAdapter getAdapter() ** 这个方法，我还在用 2.4.3 版本，里面只有 ** RecyclerView.Adapter getAdapter()** 这个方法，明白啦~ 
谢谢~

**Comment by drakeet** [comment]
对于 2.4.3 版本，可以将 getAdapter 结果转型为 MultiTypeAdapter. 但更建议升级到 2.5 或 3.0 版本。
