### ISSUE TITLE
请问为什么没有在onBindViewHolder里面返回position

### ISSUE THREAD

**Issue by renk100** [drakeet/MultiType#140]
要在adapter里面获取position，只能通过getPosition(),当初设置如此的原因何在？？

**Comment by drakeet** [comment]
wiki 中写得很清楚：
https://github.com/drakeet/MultiType/wiki/Android-MultiType-3.0#q--a

Q：如何在 ItemViewBinder 中获取到 item position？

A: 从 v2.3.5 版本开始，只需要在你的 ItemViewBinder 子类里调用 getPosition(holder) 方法即可。另外，你也可以调用 holder.getAdapterPosition() 或 holder.getLayoutPositio() 获得可靠的 position.
