### ISSUE TITLE
关于Item 局部刷新

### ISSUE THREAD

**Issue by Sting926** [drakeet/MultiType#141]
查看您的源码发现ItemViewBinder里只有
protected abstract void onBindViewHolder(@NonNull VH holder, @NonNull T item);方法实现，没有局部刷新的方法，是有什么原因么，请教。

**Comment by Sting926** [comment]
Override     protected void onBindViewHolder(
        @NonNull VH holder, @NonNull T item, @NonNull List<Object> payloads) {
        onBindViewHolder(holder, item);
    }
可以局部刷新

**Comment by ghost** [comment]
怎么实现的局部刷新啊

**Comment by drakeet** [comment]
参见：#150 
![image](https://user-images.githubusercontent.com/5214214/27580650-e9a30af8-5b5d-11e7-8059-dcd180e8a092.png)

**Comment by drakeet** [comment]
@Greathfs 我不知道你所谓的局部刷新指的是 items 内某一些 item 批量刷新，还是单个 item 内容局部刷新，如果是前者，使用 adapter.nofityXXX 系列方法，如果是后者，MultiType 提供了 payloads 版 onBindViewHolder，覆写即可，逻辑和原来 RecyclerView Adapter 一样，如有不懂请阅读其文档。

**Comment by drakeet** [comment]
@Greathfs bind payloads: https://github.com/drakeet/MultiType/blob/3.x/library/src/main/java/me/drakeet/multitype/ItemViewBinder.java#L83

**Comment by drakeet** [comment]
Sample for payloads: https://github.com/drakeet/MultiType/tree/3.x/sample/src/main/java/me/drakeet/multitype/sample/payload
