### ISSUE TITLE
在加载更多时候，加载到几十页的数据的时候oom

### ISSUE THREAD

**Issue by i91h1r** [drakeet/MultiType#142]
提示的地方是 onCreateViewHolder(PlanStepFrameBinder.java:53)

代码中53行：View root = inflater.inflate(R.layout.item_plan_step_frame, parent, false);

这个是什么原因额？

**Comment by drakeet** [comment]
这不属于 MultiType 的问题，而且你提供的信息完全不够，我无法帮你。你需要查看你加载的资源是否太大太多导致 OOM.

**Comment by hyr0318** [comment]
![Uploading 7.png…]()
![Uploading 6.png…]()

**Comment by i91h1r** [comment]
<img width="1011" alt="7" src="https://cloud.githubusercontent.com/assets/15108892/26773640/b71a8d74-49fe-11e7-8f39-bc893531b9c1.png">
<img width="1053" alt="6" src="https://cloud.githubusercontent.com/assets/15108892/26775948/bed16866-4a09-11e7-9635-7ffd6e66bc50.png">
