### ISSUE TITLE
希望增加个onViewDetachedFromWindow方法

### ISSUE THREAD

**Issue by 5hmlA** [drakeet/MultiType#145]
Hello drakeet,下个版本能否在ItemViewBinder中增加个onViewDetachedFromWindow方法，像AdapterDelegates一样，谢谢！

**Comment by drakeet** [comment]
包括 `onViewDetachedFromWindow` 在内的更多 Adapter 的方法，曾经都在 2.5 的 beta 版本 binder 内实现过，但由于在一些 case 下会出现 crash，以至于现今都没有发到正式版里。

不过我最近也在重新考虑这个事情，应该很快接下来重新尝试加入支持。

**Comment by drakeet** [comment]
目前来说，如果需要这些方法，还是建议继承 MultiTypeAdapter 来获得覆写。转发到 binder 问题诸多。

**Comment by 5hmlA** [comment]
OK，期待你的新版本

**Comment by drakeet** [comment]
Completed. Please try: v3.1.0-beta1.
