### ISSUE TITLE
你好，一个关于微博例子的疑惑

### ISSUE THREAD

**Issue by byr1991** [drakeet/MultiType#147]
在微博例子中 使用了一个FrameBinder 作为公共相同布局的binder，不同的布局类容使用withLinker 来register，那么怎么在activity中获取到FrameBinder 这对象呢？

**Comment by drakeet** [comment]
你提供一个引用就可以在 Activity 中拿到它了，但话说回来，为什么要在 Activity 中去操作 frame binder 呢。
另外，这个问题很简单，建议你自己多思考思考。

**Comment by byr1991** [comment]
@drakeet  提供一个引用？ 可以具体一下怎么弄么。通过什么来拿到这个引用。刚接触android的菜鸟，求解答哦

**Comment by byr1991** [comment]
@drakeet 还是没想到怎么拿到FrameBinder 额，在activity 中只有继承于FrameBinder 的binder，怎么通过引用来获取FrameBinder对象额。在项目中我需要往FrameBinder 传入一个参数或者一个对象到FrameBinder中作一些操作。

**Comment by drakeet** [comment]
在 Java 中，继承于 FrameBinder 的 binder 不也是 FrameBinder 对象吗？

**Comment by byr1991** [comment]
@drakeet  直接使用SimpleTextViewBinder 或者SimpleImageViewBinder 强转成FrameBinder 就可以吗？

**Comment by drakeet** [comment]
@byr1991 当然是可以，而且无须强转。Java 的强转应该用于父类转子类，你这里是子类，子类本来就是父类实例，无须强转。

**Comment by byr1991** [comment]
那SimpleTextViewBinder 和SimpleImageViewBinder 不是通过不同的类型register进去的么，那用他们中的哪个来拿到FrameBinder的引用呢？ 用其中的一个不会报空么。

**Comment by drakeet** [comment]
我不知道你在做什么，无法回答你，我想你的需求和问题应该都十分简单，建议你自己思考思考，这些内容和 MultiType 无关，它们是属于 Java 类对象的关系、通讯问题，和你的设计和需求有关。

**Comment by drakeet** [comment]
想想两个 Java 对象怎么通讯或交通吧。另外，我提供的 weibo 示例仅仅是个示例（sample），你完全可以自由修改它的源码（它不是一个库），完全可以按照你的需求进行安排，你不需要被它所局限。

**Comment by byr1991** [comment]
@drakeet  我就是想在activity中拿到FrameBinder 中的一个参数或者变量。或者从activity中把一个对象或者参数传到FrameBinder 中额。
