### ISSUE TITLE
仿支付宝刷新

### ISSUE THREAD

**Issue by lanyu007** [drakeet/MultiType#148]
drakeet大神，我想请教一下，支付宝首页参杂了很多效果在里面，其中刷新的效果采用了中段刷新，上拉联动的方案进行页面的展示，这个是怎么实现的？

**Comment by lanyu007** [comment]
我现在外层用的scrollview，里面包了一层SwipeRefreshLayout，SwipeRefreshLayou里面再包了一层RecyclerView，这样貌似实现不了这样的效果，滑动冲突也不知道怎么解决，可以指导一下我吗

**Comment by drakeet** [comment]
请使用 CoordinatorLayout + RecyclerView 实现。另外，这里不适合此类需求讨论，如有问题，请给我发邮件。
