### ISSUE TITLE
如何实现单个binder内的数据刷新？

### ISSUE THREAD

**Issue by chenzixue** [drakeet/MultiType#150]

**Comment by drakeet** [comment]
改变 adapter 绑定的 items 内的对应数据，然后调用 adapter.notifyDataSetChanged().

**Comment by ghost** [comment]
我只想更新这一块数据列表，adapter.notifyDataSetChanged().这个不是把整个数据列表全更新一遍吗？

**Comment by drakeet** [comment]
@Greathfs 那你就使用 `adapter.notifyItemRangeChanged(positionStart, itemCount)`，这不是很明显的 API 吗？
