### ISSUE TITLE
header和footer怎么加呢

### ISSUE THREAD

**Issue by tigerface** [drakeet/MultiType#153]
header和footer也要作为item加进去么？感觉有点复杂呢

**Comment by drakeet** [comment]
**HeaderView、FooterView**

  **MultiType** 其实本身就支持 `HeaderView`、`FooterView`，只要创建一个 `Header.class` - `HeaderViewBinder` 和 `Footer.class` - `FooterViewBinder` 即可，然后把 `new Header()` 添加到 `items` 第一个位置，把 `new Footer()` 添加到 `items` 最后一个位置。需要注意的是，如果使用了 Footer View，在底部插入数据的时候，需要添加到 `最后位置 - 1`，即倒二个位置，或者把 `Footer` remove 掉，再添加数据，最后再插入一个新的 `Footer`.
(https://github.com/drakeet/Effective-MultiType)

**Comment by dingbuoyi** [comment]
@drakeet 
https://github.com/drakeet/Effective-MultiType 无法访问

**Comment by dingbuoyi** [comment]
解决方案可以参考我写的这篇文章: https://www.jianshu.com/p/4c60a26cf02f
