### ISSUE TITLE
为什么我把库引入到项目中，运行就崩溃了？

### ISSUE THREAD

**Issue by xq598359628** [drakeet/MultiType#154]
引入的方式
` compile('me.drakeet.multitype:multitype:3.1.0', {
        exclude group: 'com.android.support'
    })
  compile 'com.android.support:recyclerview-v7:22.2.0'
`
代码都是从大神您这里拷的
Activity:
`
public class Test2Activity extends BaseActivity {

    private RecyclerView mRv;
    private MultiTypeAdapter mAdapter = new MultiTypeAdapter();
    private Items mItems = new Items();

    @Override
    protected void injectContentView() {
        super.injectContentView();
        setContentView(R.layout.item_2);

        mAdapter.register(TextItem.class, new TextItemViewBinder());

        for (int i = 0; i < 100; i++) {
            mItems.add(new TextItem("hello" + i));
        }
        mAdapter.setItems(mItems);
        mAdapter.notifyDataSetChanged();
    }

    @Override
    protected void injectViews() {
        super.injectViews();
        mRv = bindView(R.id.rv);
    }
}

public class TextItem {

    public @NonNull
    final String text;

    public TextItem(@NonNull String text) {
        this.text = text;
    }
}
public class TextItemViewBinder extends ItemViewBinder<TextItem, TextItemViewBinder.TextHolder> {
    static class TextHolder extends RecyclerView.ViewHolder {

        private @NonNull
        final TextView text;

        TextHolder(@NonNull View itemView) {
            super(itemView);
            this.text = (TextView) itemView.findViewById(R.id.title);
        }
    }

    @NonNull @Override
    protected TextHolder onCreateViewHolder(@NonNull LayoutInflater inflater, @NonNull ViewGroup parent) {
        View root = inflater.inflate(R.layout.item_1, parent, false);
        return new TextHolder(root);
    }

    @Override
    protected void onBindViewHolder(@NonNull TextHolder holder, @NonNull TextItem textItem) {
        holder.text.setText("hello: " + textItem.text);
        Log.d("demo", "position: " + getPosition(holder));
        Log.d("demo", "adapter: " + getAdapter());
    }
}
`
运行该Activity，页面空白。然后随便在页面点击，崩溃...
`java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView$LayoutManager.canScrollHorizontally()' on a null object reference
                                                                            at android.support.v7.widget.RecyclerView.onInterceptTouchEvent(SourceFile:2022)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)`

还偶尔报另外一个错
非法状态异常 .you should not call this method ,Call RecyclerView.Adapter#onBindViewHolder(holder, position, payloads) instead

**Comment by drakeet** [comment]
你没有给 RecyclerView 设置 LayoutManager. 我记得是 23 版以上的 support 库才支持直接在 XML 布局文件中声明 LayoutManager.

**Comment by drakeet** [comment]
你需要自行给 RecyclerView 设置 LayoutManager.

**Comment by drakeet** [comment]
另外，看你提供的凌乱的代码，你没有初始化 RecyclerView. 需要自行初始化 RecyclerView 并 setAdapter.

**Comment by xq598359628** [comment]
`public class Test2Activity extends BaseActivity {

    private RecyclerView mRecyclerView;
    private MultiTypeAdapter mAdapter;
    private Items mItems = new Items();
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mRecyclerView = (RecyclerView) findViewById(R.id.rv);
        LinearLayoutManager manager = new LinearLayoutManager(this);
        mRecyclerView.setLayoutManager(manager);
        mAdapter = new MultiTypeAdapter();
        mAdapter.register(TextItem.class,new TextItemViewBinder());
        mRecyclerView.setAdapter(mAdapter);
        mAdapter.setItems(mItems);

        for (int i = 0; i < 50; i++) {
            mItems.add(new TextItem("hello" + i));
        }
        mAdapter.notifyDataSetChanged();

    }

    @Override
    protected void injectContentView() {
        super.injectContentView();
        setContentView(R.layout.test2);
    }
}`
大神，这次我设置了LayoutManager,不过还是报错了..
   java.lang.IllegalAccessError: You should not call this method. Call RecyclerView.Adapter#onBindViewHolder(holder, position, payloads) instead.
                                                                        at me.drakeet.multitype.d.onBindViewHolder(SourceFile:225)
                                                                        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(SourceFile:5084)
                                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:4385)
                                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:4278)

**Comment by xq598359628** [comment]
因为项目有混淆，而且没法去，所以我也不能具体定位到源码哪一行

**Comment by drakeet** [comment]
你试试 23 版的 support:recyclerview

**Comment by xq598359628** [comment]
项目中一直用的
![default](https://user-images.githubusercontent.com/19554410/27903806-36fb5600-626d-11e7-84bc-27d0448d3769.png)
我也没法改，这怎么弄..

**Comment by drakeet** [comment]
那你需要查询一下 22 版 RecyclerView Adapter 有没有 `onBindViewHolder(VH holder, int position, List<Object> payloads)` 这个方法。

**Comment by xq598359628** [comment]
从源码里搜了下这个方法，没有第三个参数

**Comment by drakeet** [comment]
那只能说不支持 22 版 RecyclerView 了。没办法，这是 RecyclerView API 级别的变更导致无法兼容，感谢你的反馈！我测试下，如果属实，将会在 README 标示不兼容 22 版及以下的 RecyclerView.

**Comment by xq598359628** [comment]
这真是一个悲伤的故事...

**Comment by drakeet** [comment]
你们升级一下 RecyclerView 就好了，我们都在使用 26 版的 RecyclerView 了，完全没问题。

**Comment by xq598359628** [comment]
我们项目COMPILE_SDK_VERSION = 22，这个好像不能升吧...

**Comment by xq598359628** [comment]
![default](https://user-images.githubusercontent.com/19554410/27904327-f3f776f2-626e-11e7-8fcf-2858d547a627.png)
我把大神您这里方法改下是不是就可以了

**Comment by drakeet** [comment]
![image](https://user-images.githubusercontent.com/5214214/27904316-eca5e712-626e-11e7-9496-b56071eac07e.png)
根据官方文档说明，payloads 版 onBindViewHolder 是在 23.0.0 才加入的。

如果你们受限于 compileSdkVersion，把它改到 23 或以上就好了，我们都使用 25 或 26 了。

**Comment by xq598359628** [comment]
悲伤的故事...我们项目很庞大，不是我想升就能升的..

**Comment by drakeet** [comment]
payloads 是一定要支持的，22 版 RecyclerView 没有 `onBindViewHolder(VH holder, int position, List<Object> payloads)`，那只能被放弃了。你可以自行修改源码来支持，但这么做会破坏 MultiType 的整体设计，如果你不了解其牵扯面的话，可能导致出错，也会与后续更新断层。

**Comment by drakeet** [comment]
我们不会为了你们项目永远只用 22 版 support 库而不去支持 22 版以上的 support libraries.
