### ISSUE TITLE
adapter.register注册了还是报registered错误

### ISSUE THREAD

**Issue by renk100** [drakeet/MultiType#159]
What kind of issue is this?

 - [ ] 注册代码如下：
        MultiTypeAdapter multiTypeAdapter;
        List<Object> mItems;
        mItems = new Items();
        multiTypeAdapter = new MultiTypeAdapter(mItems);
        multiTypeAdapter.register(MomentsBean.class, new MomentsViewBinder());
继承：
public class MomentsViewBinder extends ItemViewBinder<MomentsBean, MomentsViewBinder.ViewHolder>{}

MomentsBean里面 没有泛型。
 - 错误
 me.drakeet.multitype.BinderNotFoundException: Do you have registered the binder for ArrayList.class in the adapter/pool?  at me.drakeet.multitype.MultiTypeAdapter.indexInTypesOf(MultiTypeAdapter.java:250)
                                                               at me.drakeet.multitype.MultiTypeAdapter.getItemViewType(MultiTypeAdapter.java:192)

 - [ ] 
###### Info:

 - MultiType version: 3.0.1 library
 - Device OS version: all
 - Device Name:

**Comment by drakeet** [comment]
> Do you have registered the binder for **ArrayList.class** in the adapter/pool?

你如何 add 数据到 items 里的？

**Comment by drakeet** [comment]
你是不是 `mItems.add(anotherList)`？你如果你要往 mItems add 一个 list，你应该使用 `mItems.addAll(anotherList)`.

**Comment by renk100** [comment]
对。犯了这个低级错误。应该是用addAll。其他地方都是用addall的。

**Comment by drakeet** [comment]
所以学会看错误信息很重要，实际上错误日志中透露的信息已经很明白了。

**Comment by wangzhiyuan** [comment]
现在有这种场景需求，能直接注册list类型吗？
