### ISSUE TITLE
TypeItem 的作用？

### ISSUE THREAD

**Issue by 70kg** [drakeet/MultiType#16]
hi   @drakeet 我想问一下`TypeItem`的作用是什么，为什么不直接使用`ItemContent`而是还要再包装一层，还有`extra`这个字段的意义是什么呢?  是在`onBindViewHolder`的时候用于区分？谢谢

**Comment by drakeet** [comment]
再包一层带来了巨大的拓展性和对所有 Item 统一配置的可能，看看我的 TimeMachine 你就知道了，TimeMachine 在对 Content 没有任何侵入的情况下，将 ItemType 拓展为 Message.

**Comment by drakeet** [comment]
[drakeet/TimeMachine](https://github.com/drakeet/TimeMachine) bases on MultiType v1.2

`Message extends TypeItem`: https://github.com/drakeet/TimeMachine/blob/master/timemachine/src/main/java/me/drakeet/timemachine/Message.java

`MessageViewProvider<C extends ItemContent, V extends RecyclerView.ViewHolder>
    extends ItemViewProvider<C, V>`: 
https://github.com/drakeet/TimeMachine/blob/master/timemachine/src/main/java/me/drakeet/timemachine/MessageViewProvider.java

**Comment by drakeet** [comment]
2.0 版本已去掉二层数据结构：https://github.com/drakeet/MultiType/releases/tag/v2.0.0

由原来的两层数据结构改为一层，对于大众来说更加简单好用了，同时提供了二次分发、扁平化的实现接口，升级改动也比较简单。拥有较复杂数据结构的 TimeMachine 也已经适配成功了。
