### ISSUE TITLE
Items.class is not necessary to be put  in the library module

### ISSUE THREAD

**Issue by kxfeng** [drakeet/MultiType#161]
What kind of issue is this?
 - [x] Feature Request

###### Info:

 - MultiType version: 
v3.2.0

###### Description: 
`Items.class` is just a `ArrayList<Object>`, I think it's only used to increase readability.  This class is not used anywhere in the library module, but the sample module. 

###### My thoughts: 
I think it's better to remove it from the library module, if user need this simple class they can create it self.

**Comment by drakeet** [comment]
Thanks, you are right, but keeping it is better.

**Comment by drakeet** [comment]
The `Items` has been removed since `v4.0.0`, see #253 and https://github.com/drakeet/MultiType/blob/master/CHANGELOG.md#version-400-alpha2---feb-06-2019
