### ISSUE TITLE
[sample] Sample 中 MultiSelectActivity 存在选中状态丢失问题

### ISSUE THREAD

**Issue by LoveqLRC** [drakeet/MultiType#164]
- MultiType version: 3.3.0
 - Device OS version: 5.1.1
 - Device Name: 华为TL00H

###### Description: 
例如选中特别番中的2，此时2选中状态，如果滚到底部，然后再次往上滚动，点击2，需要点击>2次才能取消选中。

**Comment by drakeet** [comment]
这属于示例 bug，感谢反馈！

**Comment by drakeet** [comment]
Marked as Fixed.
