### ISSUE TITLE
recyclerview数据重绘的小问题

### ISSUE THREAD

**Issue by wying111** [drakeet/MultiType#166]
我首页用一个rec，然后依次注册布局，
` mAdapter = new MultiTypeAdapter();
        mAdapter.register(BannerData.class, new BannerBinder());
        mAdapter.register(SimpleTitle.class, new SimpleTitleBinder());
        //mAdapter.register(TGirl.class, new TGirlItemBinder());
        mAdapter.register(Topic.class, new TopicItemBinder());
        mAdapter.register(NodesData.class, new NodeBinder());`
我请求数据的时候只更新topic,为什么node的数据也会重新绘制一遍呢，例如我请求了节点列表和话题列表，在回调话题列表的时候刷新rec，这个时候是没问题的，但是往下拉，加载更多的时候，滑倒最上面，节点列表假设只有12个数据，它会绘制24个，再次下拉，会绘制36个，但是数据里的节点类型数据个数就是12个，这个您知道为什么吗？谢谢。

**Comment by drakeet** [comment]
你是怎么更新的？MultiType 只是很薄的一层类型分发层，它绝不会去影响你的刷新逻辑和子 View 内容。你说的情况没有关联的代码，无法帮助你。

**Comment by drakeet** [comment]
另外，我不明白你说的“绘制 XX 个”是什么意思，请提供演示视频或图片及相关的可直接运行复现的代码。

**Comment by wying111** [comment]
![device-2017-09-04-173356](https://user-images.githubusercontent.com/20534463/30021089-bd65cfcc-9198-11e7-98f8-60199fa7d769.png)
![device-2017-09-04-173243](https://user-images.githubusercontent.com/20534463/30021094-bfdd75a2-9198-11e7-93c0-8411bd91270d.png)



所有的类型都是用MultiType注册的，这个专题我只请求了一次，然后滑动加载更多新闻列表，诡异的是，每次加载新闻，专题下所有的小节点都会加载一次，这个，不知道咋回事啊...

这是专题的绑定代码
`
public class NodeBinder extends ItemViewBinder<NodesData, NodeBinder.VH> {
    @NonNull
    @Override
    protected VH onCreateViewHolder(@NonNull LayoutInflater inflater, @NonNull ViewGroup parent) {
        View view = inflater.inflate(R.layout.explore_nodes, parent, false);
        return new VH(view);
    }

    @Override
    protected void onBindViewHolder(@NonNull VH holder, @NonNull NodesData item) {
        holder.setData(item.getNodeList());
    }

    static class VH extends RecyclerView.ViewHolder {

        FlexboxLayout mFlexboxLayout;
        Context context;

        public VH(View itemView) {
            super(itemView);
            context = itemView.getContext();
            mFlexboxLayout = (FlexboxLayout) itemView.findViewById(R.id.flexBoxLayout);
        }

        public void setData(List<Node> nodes) {
            TextView tv;
            for (Node node : nodes) {
                tv = new TextView(context);
                FlexboxLayout.LayoutParams lp = new FlexboxLayout.LayoutParams(
                        ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT);
                lp.setMargins(8,8,8,8);
                tv.setLayoutParams(lp);
                tv.setText(node.getName());
                tv.setTextColor(context.getResources().getColor(R.color.jianshu_red_color));
                tv.setBackgroundResource(R.drawable.jianshu_topic_tv_bg);
                tv.setPadding(15,10,15,10);

                tv.setOnClickListener(v->{
                    NodeActivity.startAction((Activity) context,node.getId());
                });
                mFlexboxLayout.addView(tv);
            }
        }
    }
}`，

**Comment by drakeet** [comment]
抱歉，我依旧没有看到你是如何刷新的代码。你是调用 `notifyDataSetChanged()` 刷新数据？
另外，你的格式有点乱，请在发布之前预览和调整一下，谢谢！

**Comment by drakeet** [comment]
另外，由于 RecyclerView 的复用机制，你这么写肯定有问题：
```
mFlexboxLayout.addView(tv);
```
会导致在 itemView 被复用时，比如列表滚动、列表刷新，都会触发复用机制，重新绑定数据，RecyclerView 会自动调用 onBindViewHolder()，就产生了重复 Add 事件。
这不属于 MultiType 的问题，因为不管你用原生 RecyclerView Adapter 还是 ListView，按照你这么写，都会出现这个问题。

**Comment by drakeet** [comment]
你可以考虑 setData 起始时，调用 `ViewGroup#removeAllViews()`，或者进行 diff 操作。

**Comment by wying111** [comment]
ok,我知道了，感谢您的解答。

**Comment by drakeet** [comment]
不客气，很高兴能帮助到你。
