### ISSUE TITLE
[sample]示例代码MultiSelectActivity中toast提示"3335", 我觉得我们应该期望“3 5”这样的样式

### ISSUE THREAD

**Issue by TianDehua** [drakeet/MultiType#167]
What kind of issue is this?

 - [ ] Question. toast提示"3335", 我认为我们是期望“3 5”这样的样式

###### Info:

 - MultiType version: 
 - Device OS version: 
 - Device Name: 

###### Description: 
我觉得这个问题是在 MultiSelectActivity.java:95, 这里我们写了content.append(number + ' '); //number + ' '返回仍然是一个int

###### My thoughts: 
修改为 content.append(number + “ ”); //返回为String

**Comment by drakeet** [comment]
原来如此，这算是一个小跳蚤 :P 十分感谢！
