### ISSUE TITLE
添加selectableItemBackground，没有点击效果。

### ISSUE THREAD

**Issue by i91h1r** [drakeet/MultiType#168]
- MultiType version: 3.3.0
 - Device OS version: 6.0.1
 - Device Name: 魅蓝E3

###### Description: 
在binder 的条目布局中添加 android:background="?android:attr/selectableItemBackground" 设置点击事件，在手机上不会显示点击的效果。

使用recycleview.Adapter 在其Item 布局中添加这个属性，点击item 会有效果。

**Comment by drakeet** [comment]
当你没有设置 OnClickListener 时，点击效果是不会触发的，这无关于是否使用 MultiType，MultiType 只是很薄的一层类型分发层，它绝不会影响你的 Views 内容及其逻辑。
