### ISSUE TITLE
请问类似QQ说说/朋友圈列表比较好的实现思路

### ISSUE THREAD

**Issue by renk100** [drakeet/MultiType#172]
列表包括用户头像，用户名字，时间，发表文字内容，多张图片，点赞人数列表，评论列表。   看你的sample，中没有这么复杂的列表。感觉需要recyclerview嵌套才能很好的解决。因服务器返回数据是一个消息列表（一条消息就是一个item的全部内容）。如果按照不同类型register的话。要自己拆分组装很多数据。
而且，Items.add的顺序还不能乱。很不方便。如果用gridManager动态改变列数，要加很多判断和设置margin(比如多张图片与上下type不是对齐的)等。请问有好的思路嘛。

**Comment by drakeet** [comment]
请见 sample 中的微博模块。

**Comment by renk100** [comment]
恩，如你所讲的在一级item里面嵌套一个fragment作为文字与图片的切换,但是这边图片显示的是多张，是布局先写死还是根据给的url数量动态添加？如果是需要同时显示文字与多张图片那么 用Linearlayout.addView添加布局？还有多条评论呢，怎么实现。还望指点。谢谢

**Comment by drakeet** [comment]
建议：凡是有需要不定条目数的内容，都应该用 RecyclerView，可以嵌套，包括“评论”、“附带图片”。RecyclerView 可以 wrap content，很合适。

**Comment by renk100** [comment]
我之前是嵌套，在adapter的item中创建recyclerview，担心性能问题，所以过来请教一下你了。谢谢耐心回复！

**Comment by Xbigfat** [comment]
请问,如同 weibo demo 一样的,在 content 中,能否放置girdview?我放置了 girdview 后,发现不能很好的控制content的高度,造成内容被截断.是否改用recyclerview即可? content类型是 linearlayout
