### ISSUE TITLE
大神 您好， 使用是有版本限制吗？

### ISSUE THREAD

**Issue by yuehongjie** [drakeet/MultiType#173]
大神 您好， 使用是有版本限制吗？ 我的 Android 4.4.2  HUAWEI MATE 7  直接崩溃，5.0 以上没有问题

recyclerview-v7:24.0.0
recyclerview-v7:25.2.0

都不行...

**Comment by drakeet** [comment]
没有版本限制，只要 RecyclerView 23 以上即可。
请提供复现程序和异常日志。

**Comment by yuehongjie** [comment]
实在不好意思大神 ， 排查了各种原因，没想到是我自定义的点击的水波纹效果（5.0以上有效），会造成 5.0 以下的崩溃.....

`<ripple xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:color="#aeacac"
    tools:targetApi="lollipop">
    <item android:drawable="@drawable/common_background"/>
</ripple>`

我以为是 5.0 以上才有效，没想到 5.0 以下会崩溃？？？？？

**Comment by drakeet** [comment]
是的，ripple 只支持 5.0 以上。
