### ISSUE TITLE
SeldomUsedApisPlayground  has  some bugs

### ISSUE THREAD

**Issue by AweiLoveAndroid** [drakeet/MultiType#174]
SeldomUsedApisPlayground这个类有一些bug,请博主更新，
我运行了demo，切换到这个类之后，打开studio分析工具，内存暴涨，出现了内存泄漏，然后改了一下
 protected void onViewDetachedFromWindow(@NonNull TextHolder holder) {
            appendTerminalLine("onViewDetachedFromWindow: == " + holder.text.getText());
        }
改成了 protected void onViewDetachedFromWindow(@NonNull TextHolder holder) {
            appendTerminalLine("onViewDetachedFromWindow: == " + terminal.getText());
        }
出现了OOM，
然后又把onViewDetachedFromWindow，onFailedToRecycleView里面的 appendTerminalLine("onViewDetachedFromWindow: == " + holder.text.getText());换成了appendTerminalLine("onViewDetachedFromWindow: == " + terminal.getText());改了一下， 直接应用程序无响应ANR
希望博主能把这个完善一下。

**Comment by drakeet** [comment]
SeldomUsedApisPlayground 并没有内存泄露，请提供内存泄露路径和最终泄露引用；内存爆涨并不等于内存泄露。另外，terminal 存储的是所有日志信息，你这么修改肯定会造出问题的。
