### ISSUE TITLE
Kotlin中如何使用withClassLinker注册

### ISSUE THREAD

**Issue by appdev** [drakeet/MultiType#184]
在Kotlin中使用withClassLinker注册一对多的时候return 相关的adapter的时候一直报错。哪有有成功使用withClassLinker注册成功的先例吗？

**Comment by drakeet** [comment]
@fython

**Comment by drakeet** [comment]
我用 Java 使用 withClassLinker 没有遇到问题。Kotlin 没测试过，不知道怎么回事，你能提供相关代码吗？

**Comment by drakeet** [comment]
前天还在说这个事情：
![image](https://user-images.githubusercontent.com/5214214/32222888-fcc060ce-be75-11e7-97ba-c3fc1d0a7cc7.png)

另外，图片中所说的 position 参数已经在 3.4.0-rc1 中提供了。

**Comment by linzhengloser** [comment]
![image](https://user-images.githubusercontent.com/12724989/32223030-aac8e9de-be76-11e7-8621-828d8ef4df69.png)
我在Kotlin里面是这么写的。

**Comment by drakeet** [comment]
你这代码看起来很奇怪...，报什么错？

**Comment by linzhengloser** [comment]
我没报错，我看@huclengyue 他说他的报错，我把我写的个他参考参考。

**Comment by drakeet** [comment]
@linzhengloser 原来如此，抱歉，我以为你们两个是同一个人 :p 另外，谢谢你的协助！

**Comment by appdev** [comment]
@drakeet 
我现在是使用withLinker 代替的，使用withClassLinker会提示
```
Type mismatch.
Required:
Class<out ItemViewBinder<Recommend!, *>!>
Found:
RecTextCardViewBinder
```

我的RecTextCardViewBinder肯定是继承了ItemViewBinder，可能是由于泛型的原因？
adapter注册代码
```
     adapter.register(Recommend::class.java).to(
                RecImageCardViewBinder(),
                RecTextCardViewBinder(),
                RecFollowCardViewBinder(),
                RecVideoCardViewBinder()).
                withClassLinker{ _, t ->
                    when (t.mediaType) {
                        MediaType.TEXT -> RecTextCardViewBinder()
                        MediaType.IMAGE ->  RecImageCardViewBinder()
                        MediaType.VIDEO ->  RecVideoCardViewBinder()
                        MediaType.AUDIO ->  RecTextCardViewBinder()
                        MediaType.FOLLOW ->  RecFollowCardViewBinder()
                        else ->  RecTextCardViewBinder()
                    }
                }
```

**Comment by drakeet** [comment]
@huclengyue 你返回的类型不对，应该返回 binder class 对象，而你返回的是 binder 对象。这点在使用 Java 时，编译之前就会被 IDE 检测出来返回类型错误了。Kotlin 居然能够编译通过？

**Comment by appdev** [comment]
呃呃。。我之前是直接把Java 代码复制过来直接转Kotlin的，IDE自动返回了一个对象，我没有想，直接用了对象。见笑了。我试了一下确实好了
