### ISSUE TITLE
关于分割线的问题

### ISSUE THREAD

**Issue by ruhaly** [drakeet/MultiType#185]
要是一个界面上有多个列表，每个列表的样式还不一样，比如分割线的样式，一个列表是水平，一个列表是垂直之类的，这种改咋弄呢，之前我都是通过放到header里面去处理的，现在如果用这个咋弄呢,  一个recycleview 只能设置一个Decoration

**Comment by linzhengloser** [comment]
RecyclerView 可以设置多个ItemDecoration 。而且 在 ItemDecoration 中可以通过判断 Item 的 类型来设置不同的边距。

**Comment by drakeet** [comment]
调用 `addItemDecoration()` 方法即可设置多个 `ItemDecoration`，另外，你可以参考我写的一个 `DividerItemDecoration`：

https://github.com/android-links/about-page/blob/master/library/src/main/java/me/drakeet/support/about/DividerItemDecoration.java

**Comment by ruhaly** [comment]
谢谢 群猪，回复的这么快
