### ISSUE TITLE
MultiType 使用过程遇到的问题，数据位置错乱

### ISSUE THREAD

**Issue by chenyp1994** [drakeet/MultiType#186]
![5a92af5682e2f8c737d8e93838387477](https://user-images.githubusercontent.com/12231087/32480480-b0696ade-c354-11e7-902c-44e986f57762.jpg)
![91ad5fc40333878aa0674e66f2efb6a7](https://user-images.githubusercontent.com/12231087/32480485-b30791da-c354-11e7-94e6-e93d32483d64.png)
![9638b54cfd1c481da3c42294c9618659](https://user-images.githubusercontent.com/12231087/32480487-b4887a24-c354-11e7-9d42-7a9da3a37b8a.png)

数据位置是错乱。
![3e35b41cb859df046badf8ba37663dc5](https://user-images.githubusercontent.com/12231087/32480512-d458cd68-c354-11e7-8a0d-89284d3cac03.png)

**Comment by chenyp1994** [comment]
例子都是按照Demo的例子去处理的。我不确定到底是哪里出问题。前面的数字代表他对应的位置。

**Comment by drakeet** [comment]
你的 `LinearLayoutManager` 有问题，你是不是设置了 `reverseLayout`？

**Comment by chenyp1994** [comment]
直接配置app:layoutManager，默认的。

**Comment by chenyp1994** [comment]
[SVID_20171107_150522.mp4.zip](https://github.com/drakeet/MultiType/files/1448972/SVID_20171107_150522.mp4.zip)
这个是一个手机小视频，我排查了一个上午，都没找到问题出现在哪里。我不知道是不是我哪里设置处理问题。
20个/页的数据。

**Comment by drakeet** [comment]
请发出你的布局，看是不是有 app:reverseLayout="true"

**Comment by chenyp1994** [comment]
![88cf629bf2c6547290a34c870a6be0f6](https://user-images.githubusercontent.com/12231087/32481321-8128b910-c358-11e7-8af2-544f3df9f619.png)
这个是RecycleView的布局设置。

**Comment by drakeet** [comment]
那你的 BaseRvAdapter 里做了什么？

**Comment by drakeet** [comment]
另外，你这片代码片段是在哪里：

![image](https://user-images.githubusercontent.com/5214214/32481404-1f57b580-c3ce-11e7-8f6f-247dd34f0218.png)

**Comment by chenyp1994** [comment]
不好意思，打扰你这么长时间。- -，尴尬。我刚发现问题出现在哪里了。谢谢你抽空出来回答我的问题。

**Comment by chenyp1994** [comment]
这个是ItemViewBinder里面的代码。

**Comment by drakeet** [comment]
好的，不是 MultiType 的问题吧？如果可以请说明下原因。

**Comment by chenyp1994** [comment]
不是，我已经解决了，真对不起。。

**Comment by drakeet** [comment]
我看你的代码片段，你为什么要这么做：
![image](https://user-images.githubusercontent.com/5214214/32481471-7033f4c8-c3ce-11e7-9cd3-f987127462b5.png)
明明直接有 articleModel 方法参数，你为什么还要自己去 get？

**Comment by drakeet** [comment]
麻烦你最好说一下原因，否则关注这个项目的人恐怕会以为是 MultiType 导致的问题。

**Comment by chenyp1994** [comment]
原因是因为我使用ButterKnife在onCreateViewHolder的时候进行绑定，导致数据错乱，在ViewHolder的构造方法里面操作。就不会出现我刚才的错误。
![](https://user-images.githubusercontent.com/5214214/32481471-7033f4c8-c3ce-11e7-9cd3-f987127462b5.png)
这一段代码段我只是想判断一下，是不是位置的不对导致的。忘记改掉了。

**Comment by drakeet** [comment]
好的，感谢！
