### ISSUE TITLE
提过的问题咋没了

### ISSUE THREAD

**Issue by ruhaly** [drakeet/MultiType#187]
之前提过一个问题就是：
如果遇到那种复杂的界面，比如淘宝首页的那种 该怎么弄比较好呢，

**Comment by drakeet** [comment]
可以使用 MultiType，划区块整体作为一个个 item type。也可以使用阿里开源的 https://github.com/alibaba/vlayout 来实现。MultiType 会更清晰简单，vlayout 更适用于特别复杂多变的类淘宝页面。

都能实现，看具体场景和喜好了。

**Comment by ruhaly** [comment]
楼主 知道 BaseRecyclerViewAdapterHelper 这个库么，看了你们思路都差不多哦

**Comment by drakeet** [comment]
@ruhaly 对于 BaseRecyclerViewAdapterHelper 不予置评...

MultiType 的源码、对一对多的完美支持、sample 摆在这，它一丝不苟，设计精巧，成熟可靠，好不好很明显。
