### ISSUE TITLE
4.3 奔溃（滑动），还没找到为什么。。。6.0没崩

### ISSUE THREAD

**Issue by wonxll** [drakeet/MultiType#189]
两个手机，一个6.0，一个4.3（三星 N7100）
页面多个Binder，4.3在滑动过程中，会奔溃
6.0 没问题
![image](https://user-images.githubusercontent.com/9604389/34337941-a71b1e30-e99e-11e7-86ae-4ada0f37f62c.png)

**Comment by drakeet** [comment]
请提供相关代码或可复现项目，以及你使用的 MultiType 版本号，RecyclerView 版本号。
从日志可见你并没有设置 items，导致 NPE 了。

**Comment by wonxll** [comment]
邮件发给你了。。。

**Comment by drakeet** [comment]
抱歉，我没有收到邮件，如果可以，请提供在这里，并且精简你的程序，以最小相关性提供代码能完整运行并复现你所说的状况。

**Comment by wonxll** [comment]
额～尴尬了，我先自己再找找原因。。。感谢🙏

**Comment by drakeet** [comment]
好的，不客气。我刚从邮箱垃圾箱中找到你的邮件了，谷歌认为你的邮件可能包含病毒或恶意链接，而且我看你只发给我一个 apk，这样我是没办法帮你解决问题的。

![image](https://user-images.githubusercontent.com/5214214/34338300-420d6e54-e9a2-11e7-9751-a438228738e2.png)

你可以再看看。MultiType 已经稳定运行多时，它只是很轻薄的一层类型分发层。如果需要我帮忙协助解决问题，你需要提供能直接运行并复现你状况的代码项目。

**Comment by drakeet** [comment]
你需要检查你传递的 items 是否有 null 的时候，如果你传递给 MultiTypeAdapter 一个 null 的 items 对象，它将抛出异常。

**Comment by drakeet** [comment]
针对你反馈的问题，我将提供一个新版本 MultiType，对所有要求 `@NonNull` 的参数进行入参检查，如果为 null，立马抛出异常，这样能够帮助用户更早意识到根源错误所在。你的问题想必也是因为给 MultiTypeAdapter 传递了 null 参数（尽管 MultiTypeAdapter 通过注解要求参数必须都要保证 `@NonNull`）。

等这个新版通过测试并发布，如果你还找不到问题所在，你可以尝试更新使用这个新版。它将能帮助你更精准找到问题原因。

相关 PR：https://github.com/drakeet/MultiType/pull/191

**Comment by wonxll** [comment]
谢谢，我已经找到并处理了问题，的确是我自己的原因，给你带来了问题，不好意思，也谢谢你耐心的解答

**Comment by wonxll** [comment]
谢谢，我已经找到并处理了问题，的确是我自己的原因，给你带来了问题，不好意思，也谢谢你耐心的解答@drakeet

**Comment by drakeet** [comment]
不客气
