### ISSUE TITLE
怎么注册一个带泛型的列表类型

### ISSUE THREAD

**Issue by budaowengd** [drakeet/MultiType#192]
adapter.register(ArrayList.class, new HorizontalViewBinder(this));  
我想把泛型传到ArrayList里面去，请问怎么传啊？

**Comment by drakeet** [comment]
泛型请使用一对多，或者创建一个继承类/包装类，如：

```java
public class FooList extends ArrayList<Foo> {
    ...
}
```
然后 register 这个 FooList 及其 binder 即可。
