### ISSUE TITLE
请教下数据嵌套的ViewHolder

### ISSUE THREAD

**Issue by xoptimal** [drakeet/MultiType#193]
假设我有一组数据 , 它是这样子的 :  >list[ {name :'provice', list:[ {name : 'city'}]}]

我现在注册了两个ViewHoloder ,  一个是 provice..class , 一个是 city.class

然后数据添加进去方式是 , 拆分 list , 先写 provice,  再写 city  , 从而实现这种多布局形式 , 

不过我感觉不应该这样的,  我后续的要写N多的循环来管理它们的关联关系 (PS: 要维护, 勾选啊之类的问题)

所以我感觉我这种方式是错误的,   还请指教一番 !

**Comment by drakeet** [comment]
抱歉，你的描述有点抽象或有点绕，我不太明白你的需求。

**Comment by xoptimal** [comment]
看了你的示例, 我说的是扁平化,  然后我想请问的是 , 要是我想删除省以及省下面的市 , 该怎么做比较合理,  

现在能想到的是, 在市里面做一个标记 ,  请问是这样做吗 0.0

**Comment by xoptimal** [comment]
|---provice
     |---city
     |---city
|---provice
     |---city
|---provice
     |---city

例如这样一组数据关系,   然后我将数据扁平化写进去了Adapter, 并做了对应的绑定ViewHolder

现在我要做选择省, 然后把省下面的市一并选中,   这个我该怎么写关系比较合适 ?

**Comment by drakeet** [comment]
可以使用扁平化结构，那么就是遍历修改 City list。
也可以采用 RecyclerView 嵌套 RecyclerView 结构，即 创建一个 CityList 和 CityListViewBinder。其中 City RecyclerView 高度采用 wrap_content，这样的方式也是可以的，因为 City 不可能无限多或者需要分页，因此采用嵌套更符合现实关系，也较为方便一些，与扁平化方案相比性能差距其实也很小。

**Comment by xoptimal** [comment]
明白, 感谢讲解~
