### ISSUE TITLE
How to use recyclerview inside recycerview in android OS below 5.0？

### ISSUE THREAD

**Issue by BubbleOctopus** [drakeet/MultiType#20]
Loss sub recyclerview when recyclerview inside recyclerview in os below 5.0 use meizu mobile phone in exceple, pls to checked this issue, i look forward to reply, thx.

**Comment by BubbleOctopus** [comment]
Pls test and verify this issue in meizu mobile phone and os below 5.0(4.x);

**Comment by drakeet** [comment]
I do not have a Meizu mobile phone and os below 5.0(4.x), could you test and find what happen? Or please supply more detail information.
