### ISSUE TITLE
is it possible to get current position from the adapter outside binder class?

### ISSUE THREAD

**Issue by hk4774** [drakeet/MultiType#202]
I am using a recyclerview inside a scrollview and i have to show a view after the end of the recyclerview. For smooth scrolling, I have put nestedscroll disable on recyclerview and because  of that i can not get the first/last visible item position from layoutmanager. So is there any way to get current position of the visible view from adapter from the activity?

**Comment by drakeet** [comment]
I do not understand why you can not use the layout manager.

**Comment by drakeet** [comment]
If you make the nested RecyclerView's height to wrap content, you should observer it parent ScrollView's scroll state and position.

**Comment by drakeet** [comment]
I do not understand why you are using ScrollView with RecyclerView and **MultiType**. If you need to add a View at the end of the list, just call `items.add(bottomViewItem)` and notify adapter. If the bottom view needs to be fixed at the end, your data should be added to the penultimate position.

**Comment by hk4774** [comment]
The last view is not the part of recyclerview and **MultiType** is really helpful to me as it separates out a lot of the hectic code that I have to write for multiple view types. My question is there because nither layout manager nor recyclerview is giving me the findLastCompletelyVisibleItemPosition or findLastVisibleItemPosition or findFirstCompletelyVisibleItemPosition when I'm putting recycleriview inside scrollview.
