### ISSUE TITLE
MultiTypeAdapter如何添加数据集合

### ISSUE THREAD

**Issue by tangnuo** [drakeet/MultiType#206]
MultiTypeAdapter只提供了一个setItems()，对于分段请求（多个接口返回）的数据，如何分别添加到统一的List<Object> listData中？

**Comment by drakeet** [comment]
你可以直接更新你的 items 内容，然后 notify data set changed 即可。不必要每次调用 setItems()。当初提供 setItems 方法的原因是为了提供**原子**替换整个 items 的机会。如果你在多并发操作你的 items，那么最好使用 setItems，否则你只要使用同一个 items 引用，并修改更新其内容即可。
