### ISSUE TITLE
implementation 'me.drakeet.multitype:multitype:3.4.4'冲突抛出DexArchiveMergerException

### ISSUE THREAD

**Issue by mafanwei** [drakeet/MultiType#208]
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/MultiType

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Please provide 
       your device name, device OS version, and describe the reproduction steps.

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

###### Info:

 - MultiType version: 
 - Device OS version: 
 - Device Name:

**Comment by mafanwei** [comment]
v7包

**Comment by drakeet** [comment]
请提供相关信息，否则无法知晓你的情况是什么问题导致。对于这样什么信息都不提供直接丢下一个异常名的，恕只能直接关闭。

**Comment by mafanwei** [comment]
在build.gradle中存在 
implementation 'com.android.support:support-v4:26.0.0-beta1'
 androidTestImplementation 'com.android.support.test:runner:0.5'
implementation 'me.drakeet.multitype:multitype:3.4.4'
会抛出DexArchiveMergerException
