### ISSUE TITLE
上一问题的进一步描述

### ISSUE THREAD

**Issue by mafanwei** [drakeet/MultiType#209]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/MultiType

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Please provide 
       your device name, device OS version, and describe the reproduction steps.

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

###### Info:

 - MultiType version: 3.4.4
 - Device OS version: 
 - Device Name: 

###### Description: 当build.gradle中存在：
 implementation 'com.android.support:support-v4:26.0.0-beta1'
androidTestImplementation 'com.android.support.test:runner:0.5'
implementation 'me.drakeet.multitype:multitype:3.4.4'
会抛出DexArchiveMergerException

**Comment by drakeet** [comment]
MultiType 3.4.4 依赖 27.1.0 版 support library，如果你无法使用 27 版，将它 exclude 排除掉即可。
