### ISSUE TITLE
使用gridview展示图片出现混乱

### ISSUE THREAD

**Issue by shuruncs** [drakeet/MultiType#213]
final GridLayoutManager layoutManager = new GridLayoutManager(mActivity, 3, GridLayoutManager.VERTICAL, false);
        layoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                return (items.get(position) instanceof String) ? 3: 1;
            }
        });
        adapter = new MultiTypeAdapter();
        adapter.register(String.class, new ImageTitleViewBinder());
        imageFileViewBinder = new ImageFileViewBinder(this);
        adapter.register(ImageFile.class, imageFileViewBinder);
我使用示例代码类似的标题加图片，在用 adapter.setItems(items);
            adapter.notifyDataSetChanged();更新数据后，更新后数据为一个日期标题加上三张当天的图片，三张图片并没有按照要求排成一行，第一张图片在第一行显示，其他两张随机分布在其他行
请问群主能否找下原因

**Comment by drakeet** [comment]
抱歉，这里没有群主。另外，你提供的信息不足，无法帮助你。MultiType 已经广泛运用于很多应用和场景之中，它成熟稳定，目测你的问题不属于它的问题，你需要自己再寻找原因，或者补足相关代码和描述信息。

**Comment by shuruncs** [comment]
好吧，谢谢您回复。这个问题实在是有点奇怪，我换一波数据又没有出现了
