### ISSUE TITLE
ItemViewBinder can't be recycled

### ISSUE THREAD

**Issue by zktufo** [drakeet/MultiType#214]
There is a VideoView in one of the ItemViewBinder and it was still playing when Activity destroyed.
I try to release the VideoView but failed  because `onViewDetachedFromWindow` and `onViewRecycled` was not called

**Comment by drakeet** [comment]
Impossible. You need to provide evidence and sample project. 

In addition, you can refer to the official sample:

https://github.com/drakeet/MultiType/blob/3eaf09c978fb335f9b5ecded1e8b875a513a23aa/sample/src/main/java/me/drakeet/multitype/sample/moreApis/MoreApisPlayground.java#L97-L146
