### ISSUE TITLE
ItemViewBinder里面可以做notify的操作吗？

### ISSUE THREAD

**Issue by shlockfan** [drakeet/MultiType#215]
如果我在 继承ItemViewBinder的类里面做个点击操作notifyDatasetChanged整个recyclerView，可以做这样操作吗？

**Comment by drakeet** [comment]
可以。

**Comment by shlockfan** [comment]
没有这个方法啊？

**Comment by drakeet** [comment]
ItemViewBinder#getAdapter()#notifyDataSetChanged()

**Comment by shlockfan** [comment]
是不是getAdapter().notifyDataSetChanged();

**Comment by drakeet** [comment]
是的。

**Comment by shlockfan** [comment]
多谢
