### ISSUE TITLE
Dynamic MultiType View

### ISSUE THREAD

**Issue by praveenshharma** [drakeet/MultiType#216]
How to create vertical and horizontal recyclerview dynamically ?
My approach is to create dynamic sections and their items in horizontal direction.
Is this scenario is possible with this lib ?

**Comment by drakeet** [comment]
See https://github.com/drakeet/MultiType/blob/3.x/sample/src/main/java/me/drakeet/multitype/sample/bilibili/HorizontalPostsViewBinder.java

**Comment by praveenshharma** [comment]
So can we make this with the example of bilibili activity with only one recycler view ?
{
"movies":{
  "item1","item2","item3"
   }
"tv":{
  "item1","item2","item3"
   }
"web series":{
  "item1","item2","item3"
   }
}

**Comment by drakeet** [comment]
Yes, you can.
