### ISSUE TITLE
使用setSpanSizeLookup 设置几列的时候，至始至终只能显示一列。 

### ISSUE THREAD

**Issue by xiangxm** [drakeet/MultiType#219]
使用setSpanSizeLookup 设置几列的时候，至始至终只能显示一列。 

fragRecyviewMain.setAdapter(adapter);
        final GridLayoutManager layoutManager = new GridLayoutManager(this, SUB_CATEGORY_NUMBER);
        layoutManager.setOrientation(GridLayoutManager.VERTICAL);
        fragRecyviewMain.setLayoutManager(layoutManager);
        layoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                return items.get(position) instanceof SubListBean ? SUB_CATEGORY_NUMBER : SPAN_COUNT;
            }
        });

**Comment by xiangxm** [comment]
找到原因了。

**Comment by uncleTan** [comment]
什么原因？
