### ISSUE TITLE
支持Paging Library 中的 PagedListAdapter

### ISSUE THREAD

**Issue by taosimple** [drakeet/MultiType#220]
Google推出的 [Paging Library](https://developer.android.com/topic/libraries/architecture/paging/#overview) 带有一个 PagedListAdapter 需要继承，目前好像不支持和 Paging Library 一起使用

**Comment by drakeet** [comment]
很早期的时候就考察过 Paging 以及 MultiType 是否对其进行适配，结论是，不需要，这本来就是两个互不矛盾的选择。用户如果需要 Paging 就去用 Paging，如果需要 MultiType 就 MultiType，如果需要二者结合，则自行封装、组合即可。
因此目前看来，MultiType 官方不必要对其进行适配。
