### ISSUE TITLE
焦点问题

### ISSUE THREAD

**Issue by wesley235** [drakeet/MultiType#221]
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/MultiType

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Please provide 
       your device name, device OS version, and describe the reproduction steps.

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

###### Info:

 - MultiType version: 3.4.4
 - Device OS version: 4.2.2
 - Device Name: 电视盒子

###### Description: 
使用 multitype，添加一种类型的view，该view中嵌套一个recyclerview，此时在嵌套的recyclerview中焦点无法在内部自由切换

**Comment by drakeet** [comment]
这不是 MultiType 的问题。你应该了解一下 RecyclerView 的焦点机制和 `descendantFocusability` 属性。
