### ISSUE TITLE
希望能和Paging library一起使用

### ISSUE THREAD

**Issue by dai-xun** [drakeet/MultiType#226]
如题

**Comment by artshell** [comment]
作者有时间实现吗？
既要支持Paging library功能，又要支持原始传如List这种功能，最好的做法是添加一个新的类
叫MultiTypePageAdapter结合MultiTypeAdapter + Support包中的 PagedListAdapter 这些已有实现来做

@drakeet

**Comment by drakeet** [comment]
MultiType 目前没有计划支持 Paging，理由请见：
https://github.com/drakeet/MultiType/issues/220

**Comment by drakeet** [comment]
另外，大多数使用 Paging 的场景，都不需要 MultiType，所以它们二者可以说是不冲突的、不需要合一的。

**Comment by biubiuqiu0** [comment]
大佬，使用paging 的话 就不能自主操作数据的位置了吧？比如 我已加载了10条数据，然后想在头部插一个headerview， 我看pagelist没有这种方法

**Comment by artshell** [comment]
@VongVia1209 

Paging这个功能本就是数据结构相同，连续性的数据，如果真要实现这种需求的话：
你得参照 PagedListAdapter 和 AsyncPagedListDiffer这两个类来做，
在AsyncPagedListDiffer#getItem()这个方法里根据 index来判断是否是头部，是否调用mPagedList.loadAround(index)将当前index分发给你的 DataSource.Factory去加载数据

**Comment by VongVia1209** [comment]
多谢
