### ISSUE TITLE
how to register event like click or longclick

### ISSUE THREAD

**Issue by zubinxiong** [drakeet/MultiType#23]
recyclerView's click event usually give a interface for you to register in activity, but i found in this library all adapter extends from MultiTypeAdapter class, I can't find any way to get this interface.

for example : if i left a interface setonTextClickListener in TextItemViewProvider , how can i register it in activity or is there any better way to do this?

**Comment by drakeet** [comment]
You could extends `MultiTypeAdapter` to provide the `setOnItemClickListener`, **but it is recommended that** set your `OnClickListener` in your `ItemViewProvider`. `ItemViewProvider` can touch the data and views, it is appropriate.

**Comment by zubinxiong** [comment]
thanks, it helps me a lot
