### ISSUE TITLE
sample中的bug以及一个使用问题

### ISSUE THREAD

**Issue by zhangpfan** [drakeet/MultiType#232]
**sample bug：**
MoreApisPlayground演示中，CLEAR后REMOVE，此时未能对items长度为0进行判断
public void onRemove(View view) {
    int bottom = items.size() - 1;
    recyclerView.scrollToPosition(bottom);
    items.remove(bottom);
    adapter.notifyItemRemoved(bottom);
  }

**一个使用的问题：**
正如sample中演示：实现线性布局和网格布局混排列表，此时我如何给网格布局的添加selector。
我的意思是例如：给特别篇下的1234567添加一个整体的selector。

**Comment by drakeet** [comment]
你好，你提供的 bug 和问题，都属于 RecyclerView 的问题，MultiType 只是很薄的一层类型分发层，它不会更改 RecyclerView 原生逻辑。至于你的 bug 和问题，不属于 MultiType 的范畴，在此不做解答。

**Comment by drakeet** [comment]
如果你不知道如何实现，应该去 Android 讨论组或 StackOverflow.com 进行提问和获得解答。这里只解决与 MultiType 本身有关的需求和问题。

**Comment by drakeet** [comment]
也就是说，就算你不用 MultiType，你的问题和所谓的 bug 也都仍然存在，所以它们都不属于 MultiType 的问题。

**Comment by zhangpfan** [comment]
好吧，谢谢
