### ISSUE TITLE
GridLayoutManager判断到底部加载更多的问题

### ISSUE THREAD

**Issue by finalrose7** [drakeet/MultiType#236]
当RecyclerView使用GridLayoutManager的时候，如何判断为滑动到底部了呢？我在RecyclerView的addOnScrollListener中，使用MultiTypeAdapter#getItemCount拿到的是一个不准确的值。

**Comment by Anthonyeef** [comment]
我在自己的小项目里用到了 GridLayoutManager 和 MultiType，没有遇到类似问题；也是参考了 drakeet 的 LoadMoreDelegate 的写法：https://github.com/Anthonyeef/Cattle/blob/master/app/src/main/kotlin/io/github/anthonyeef/cattle/fragment/ProfileAlbumFragment.kt#L38 

仅供参考

**Comment by finalrose7** [comment]
@Anthonyeef 嗯，谢谢。我知道是什么问题了。
