### ISSUE TITLE
是否可以将  getItemCount 方法的final 去掉

### ISSUE THREAD

**Issue by liuyouth** [drakeet/MultiType#238]
我想实现一个 可以无限循环的 banner 
需要修改这里以及 getItemViewType 
来达到无限循环的目的，只是个想法。
虽然有很多的banner 轮播 ，以及 用rv 实现的 轮播 
但是那种都需要新建很多adapter 
我想只是新建不同的ItemViewBinder 用MultiType 这种模式 构建一个banner 

不是问题，只是找不到合适的沟通方式所以在这里提出来了。

**Comment by drakeet** [comment]
抱歉，MultiTypeAdapter 并非为继承而设计，因此我无法单独为你开启某个口子，否则可能影响导致其他地方混乱或异常。你应该考虑使用组合或代理模式，而非继承。
