### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by zubinxiong** [drakeet/MultiType#24]
- when I use this library in my app, the layout like this picture. as you see, this layout contain at least one  TitleItem and GridRecyclerViewItem, sometimes the Grid has a large number over 1000 
- During test, first time I init  data to  layout, i call the notifydatasetchanged(), it has a verbose 
  ``Skipped 72 frames! The application may be doing too much work on its main thread`.  I think this problem is caused by GridRecyclerViewItem, MultiTypeAdapter needs to maintance serveal adapter, first time refresh will casue this problem.
- same layout use one normal RecyclerView with GridLayoutManager and setSpanSizeLookup will not cause this problem. If I use MultiTypePool.getProviderByIndex to achieve the same function, I think there is no different with normal Adapter,  do you hava any plan about this problem?

![image](https://cloud.githubusercontent.com/assets/7650970/18948696/b3aeb65e-866a-11e6-878e-8cb84b2ac3fd.png)

**Comment by drakeet** [comment]
I guess your `GridRecyclerViewItem` height is wrap_content, and it will cause the sub RecyclerView load all its items so that causes the block.

**Comment by drakeet** [comment]
There are two ways to solve the issue: 
- Change the sub `RecyclerView` to flat items, and a item layout looks like this: 
  ![image](https://cloud.githubusercontent.com/assets/5214214/18950700/b97b8b4e-8673-11e6-9fe4-5a7c38ddbeaf.png)
- Use `GridLayoutManager` and `setSpanSizeLookup` with `MultiType`, the `MultiType` does not specify that it must use `LinearLayoutManager`.

**Comment by drakeet** [comment]
Wait a moment, I will write a sample with the second way for you.

**Comment by drakeet** [comment]
OK, I have achieved it: 

<img src="https://cloud.githubusercontent.com/assets/5214214/18952927/9544990e-867e-11e6-97ba-8e93f0e84dba.png" width=270 height=480/>

**Comment by drakeet** [comment]
And the performance is great! I am uploading the source...

**Comment by drakeet** [comment]
The multi-grid sample:

https://github.com/drakeet/MultiType/tree/master/sample/src/main/java/me/drakeet/multitype/sample/grid

**Comment by drakeet** [comment]
And you are right, there is no big difference with the normal adapter because the MultiType is lite originally but flexible and powerful.

**Comment by zubinxiong** [comment]
Actually I already do the same effect like your suggestions2, it's same as your new sample. but I think there is no difference with origin adapter，so I just open the issues to ask for your options about the reason why you design like that，I guess maybe you didn't want to change the way to use adapter，but maybe a little encapsulates will more direct,  it's the different opinions with you .

And thanks for your answers and sample, it will also help other person

**Comment by drakeet** [comment]
The only difference is you do not need to dispatch the view types and View Holders by yourself , MultiTypeAdapter will do that.
