### ISSUE TITLE
onBindViewHolder方法没有position有点不方便,有时候需要对item的某个position特殊处理

### ISSUE THREAD

**Issue by dengzhiguiios** [drakeet/MultiType#243]
###### Info:

 - MultiType version: 3.3
 - Device OS version: 
 - Device Name: 

###### Description: 
onBindViewHolder方法没有position有点不方便,有时候需要对item的某个position特殊处理

**Comment by dengzhiguiios** [comment]
已找到解决方法

**Comment by wkboys** [comment]
如何解决的？

**Comment by drakeet** [comment]
@wkboys RV.Adapter 中有关于 position 的建议，最好不要使用 position 参数，而是使用 ViewHolder 身上的 position：

![image](https://user-images.githubusercontent.com/5214214/65122567-e1e36f00-da23-11e9-8933-e511482a9022.png)

谷歌官方文档：https://developer.android.google.cn/reference/androidx/recyclerview/widget/RecyclerView.Adapter.html#onBindViewHolder(VH,%20int)
