### ISSUE TITLE
是否可以实现RecyclerView的 Item悬浮吸顶效果？

### ISSUE THREAD

**Issue by RyanJeson** [drakeet/MultiType#244]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/MultiType

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Please provide 
       your device name, device OS version, and describe the reproduction steps.

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

###### Info:

 - MultiType version: 
 - Device OS version: 
 - Device Name:

**Comment by drakeet** [comment]
可以，但这和 MultiType 无关或不属于 MultiType 的范畴，请使用 StickyHeadersItemDecoration 或自定义 ItemDecoration 实现。

**Comment by RyanJeson** [comment]
谢谢解惑！非常喜欢实用您的库，在工作中帮助很大
