### ISSUE TITLE
RecyclerView 嵌套水平 RecyclerView 无法回调到 onViewAttachedToWindow(holder) 方法

### ISSUE THREAD

**Issue by PPTing** [drakeet/MultiType#250]
Bug report.

###### Info:

 - MultiType version: 3.5.0
 - Device OS version: MIUI 10 8.12.10 (Android 8.0.0)
 - Device Name: Mi6 小米6

###### Description: 
在竖向的RecyclerView A 嵌套 横向的 RecyclerVIew B 的情况下(例如 sample 中的 BilibiliActivity) 
横向的 B RecyclerView 中在滑动过程中，B RecyclerView 的 ViewBinder 中的 onViewAttachedToWindow(holder) 和 onViewDetachedFromWindow(holder) 方法都不会被调用

**Comment by drakeet** [comment]
这个事情没理由发生，请提供能够复现的简要程序。

**Comment by PPTing** [comment]
Sorry. 我没看仔细 sample 中的代码，原来 BilibiliActiviy 中的横向的 Adapter 不是 PostViewBinder。
这个问题不存在的。
实在不好意思，给你添麻烦了
