### ISSUE TITLE
横向recyclerview好像有滑动冲突？

### ISSUE THREAD

**Issue by tmxd09887** [drakeet/MultiType#254]
multitype:3.4.4

好像multitype库，没有特别优化滑动冲突？
横向滑动的时候，不是很流畅。我觉得理想的应该是优先横向滑动，纵向滑动不敏感更好。
有没有其他用过的同学，提供下改善的思路。

谢谢

**Comment by drakeet** [comment]
这不是这个项目的问题，那是 RecyclerView 和你的布局安排问题。MultiType 只负责类型分发，它不会改变你 View 的行为或手势交互。
