### ISSUE TITLE
当列表数据是纯String时 会报错

### ISSUE THREAD

**Issue by verzqli** [drakeet/MultiType#255]
What kind of issue is this?

 当列表数据是纯String时 register（String.class,XXXX）,会出现java.lang.Class java.lang.Object.getClass()错误
method 'java.lang.Class java.lang.Object.getClass()' on a null object reference       
  at me.drakeet.multitype.MultiTypeAdapter.indexInTypesOf(MultiTypeAdapter.java:339)

**Comment by drakeet** [comment]
你给 adapter 传递的 items 中包含 null 导致了这个问题，这不是这个项目的问题。
