### ISSUE TITLE
MultiTypeTemplates插件项目地址404

### ISSUE THREAD

**Issue by renk100** [drakeet/MultiType#256]
MultiTypeTemplates插件项目能否开源一下呢？

**Comment by drakeet** [comment]
之前被人针对过，因此 MultiTypeTemplates 这个项目已经回归闭源并不再提供，抱歉。但它仍然可以在 Idea 插件中心下载得到。

**Comment by renk100** [comment]
太遗憾了！我自己写的插件，感觉代码乱。所以想学习一下。
