### ISSUE TITLE
wiki的文档点击不进去。

### ISSUE THREAD

**Issue by weishd** [drakeet/MultiType#257]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/MultiType

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Please provide 
       your device name, device OS version, and describe the reproduction steps.

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

###### Info:

 - MultiType version: 
 - Device OS version: 
 - Device Name:

**Comment by drakeet** [comment]
感谢反馈，旧版 wiki 已不再提供，待更新新版或移除 wiki 链接。

**Comment by RyanJeson** [comment]
> 感谢反馈，旧版 wiki 已不再提供，待更新新版或移除 wiki 链接。

其实还是很多人使用3.4.4版本的，不知道旧的文档是否可以保留！

**Comment by huangyz0918** [comment]
我觉得 Java 的 Wiki 还是有必要的，如果能有 Java 源码学习一下就更好了，建议上传个 Read-only Repo 到 Github，非常感谢

**Comment by drakeet** [comment]
@huangyz0918 抱歉，不会再对最新代码提供 Java 版了。但你可以在 3.x 分支找到旧版代码，那是用 Java 实现的。

**Comment by lzjtugjc** [comment]
**感觉生成代码的插件挺好用的,现在也不会再提供了吗**

**Comment by weishd** [comment]
没有文档看，直接把这个组件放弃使用了。
