### ISSUE TITLE
我需要继承MultiTypeAdapter，但它是final的，能否加open

### ISSUE THREAD

**Issue by qiushui95** [drakeet/MultiType#259]
- MultiType version: 4.0.0-alpha2

**Comment by zhangls2014** [comment]
实现 `DiffUtils` 不是非要继承 `MultiTypeAdapter` 吧，换个思路

**Comment by drakeet** [comment]
感谢反馈，你可以使用组合替代继承，这样不容易打乱 MultiTypeAdapter 内部流程进而引起错误。不过我会考虑 open 它，并且在之后的 4.0 alpha 版本中 MultiTypeAdapter 将会支持 SortedList（谷歌官方提供的一个非实现 List 接口的容器类），它能够更好地支持 diff 和排序。

**Comment by qiushui95** [comment]
@zhangls2014 因为之前的版本就是open的  所以我直接那样写了，升级之后就不能使用了

**Comment by drakeet** [comment]
@qiushui95 4.0.0-alpha3 已生效，请试试，如果还有什么需求，欢迎另开新的 issue 提出。

**Comment by qiushui95** [comment]
@drakeet 好的。谢谢，辛苦了
