### ISSUE TITLE
[multi-grid-sample] item 选中以后，滑动错乱

### ISSUE THREAD

**Issue by android-xiaowei** [drakeet/MultiType#26]
您的sample中的MultiGridActivity中item选中以后，滑动错乱，

**Comment by drakeet** [comment]
那是因为我没有记录保存选中项目，导致复用的时候出现混乱，记录一下就好了。

**Comment by drakeet** [comment]
你可以关注这个项目获得通知，晚点我会增加记录，感谢你的反馈！

**Comment by drakeet** [comment]
抱歉，今天感冒比较严重，刚才才爬起来解决了这个 issue，代码很简单，只要在 item model 中记录一下即可，或者使用一个统一的静态容器如 `SparseArray` 来记录下标（如这么做，记得最后做集体释放，否则就内存泄露了）：

![image](https://cloud.githubusercontent.com/assets/5214214/18994434/61b61734-875a-11e6-995e-a1117e0e1a6b.png)

**Comment by android-xiaowei** [comment]
注意身体啊，我是今天运行demo的时候发现的，后来我自己也是做了标记解决了，主要是给您提醒一下，如果没有修复，后来者体验的话可能会差点。
