### ISSUE TITLE
register方法能否加上open

### ISSUE THREAD

**Issue by yushilong** [drakeet/MultiType#262]
我想继承MultiTypeAdapter，然后重写register方法实现一个自动加上footViewBinder的功能，这样滑动到底部的时候可以显示我这个footView

谢谢！

**Comment by drakeet** [comment]
这个事情不应该在 register 中进行。

**Comment by yushilong** [comment]
全局自动加上footViewBinder的功能，所有列表呢

**Comment by drakeet** [comment]
你应该在 `constructor` 或 `init {}` 中去 register 而不是去覆写 register。

**Comment by yushilong** [comment]
> 你应该在 `constructor` 或 `init {}` 中去 register 而不是去覆写 register。

好的，谢谢
