### ISSUE TITLE
聊天页面 如何左右样式合一？

### ISSUE THREAD

**Issue by bannerkun** [drakeet/MultiType#264]
看了微博例子，还是不清楚怎么处理左右布局合一的情况？

**Comment by linzhengloser** [comment]
不太明白什么是布局合一，以前用 MultiType 实现过一个简单的聊天的列表，参考的作者以前开源的一个项目(现在好像关闭了)。https://github.com/linzhengloser/CommonRepository-Android/blob/master/%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/%E8%81%8A%E5%A4%A9%E5%88%97%E8%A1%A8/README.md  希望对你有帮助。

**Comment by bannerkun** [comment]
感谢

**Comment by bannerkun** [comment]
> 不太明白什么是布局合一，以前用 MultiType 实现过一个简单的聊天的列表，参考的作者以前开源的一个项目(现在好像关闭了)。https://github.com/linzhengloser/CommonRepository-Android/blob/master/%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/%E8%81%8A%E5%A4%A9%E5%88%97%E8%A1%A8/README.md 希望对你有帮助。

就是这种样式，我现在的布局都是左右各一套，很麻烦，这框架方面的资料又少，很郁闷。多谢老哥！
