### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException 【3.4.4】【偶现】

### ISSUE THREAD

**Issue by pys200603027** [drakeet/MultiType#266]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/MultiType

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Please provide 
       your device name, device OS version, and describe the reproduction steps.

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

###### Info:

 - MultiType version: 
 - Device OS version: Android 8.1.0,level 27
 - Device Name: VIVO X9S PLUS

###### Description: 
```java
java.lang.ArrayIndexOutOfBoundsException
java.util.ArrayList.get(ArrayList.java:439)
me.drakeet.multitype.MultiTypePool.getItemViewBinder(MultiTypePool.java:143)
me.drakeet.multitype.MultiTypeAdapter.getRawBinderByViewHolder(MultiTypeAdapter.java:334)
me.drakeet.multitype.MultiTypeAdapter.onViewDetachedFromWindow(MultiTypeAdapter.java:329)
```

###### What did I do:

**Comment by drakeet** [comment]
你的 views 和 items 没有实时同步，可能你并发或异步修改了 items 导致。这不属于 MultiType 的问题，换句话说，你使用原生 RecyclerView Adapter 同样会遇到这个问题。而且由于你提供的描述和信息都非常有限，无法解决和得到准确结论。

**Comment by drakeet** [comment]
如果你需要进一步帮忙，你需要提供最小体积可直接编译运行的可复现工程。

**Comment by pys200603027** [comment]
好的，感谢作者，我这边持续关注下
