### ISSUE TITLE
使用该库，无法出效果

### ISSUE THREAD

**Issue by simon20190306** [drakeet/MultiType#268]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/MultiType

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Please provide 
       your device name, device OS version, and describe the reproduction steps.

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

###### Info:

 - MultiType version: 
 - Device OS version: 
 - Device Name:

**Comment by drakeet** [comment]
请提供复现程序，这个 issue 没有任何有效信息，无法给你解答，将关闭这个 issue。
如果页面没有内容，你应该首要检查，你是否把 adapter 设置给 RecyclerView。

**Comment by simon20190306** [comment]
问题已解决，我忘记给RecyclerView添加布局管理器，比如LinearLayoutManager。
另外，能否要下你的微信？

Drakeet <notifications@github.com> 于2019年5月5日周日 上午10:30写道：
