### ISSUE TITLE
BinderNotFoundException

### ISSUE THREAD

**Issue by zyallday** [drakeet/MultiType#271]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/MultiType

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Please provide 
       your device name, device OS version, and describe the reproduction steps.

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

###### Info:

 - MultiType version: 3.4.4
 - Device OS version: Android  通用
 - Device Name: 不限制设备

###### Description: 
```java
    BinderNotFoundException(@NonNull Class<?> clazz) {
    super("Do you have registered {className}.class to the binder in the adapter/pool?"
        .replace("{className}", clazz.getSimpleName()));
  }
```

###### My thoughts: 
这个异常在抛出的时候，打印的日志只有 class 的 simpleName, 这样导致在线上如果代码经过了混淆之后会有很多类的 simpleName 一样无法定位到底是哪个类的 Binder 没有注册，
是否可以改成这样
```java
BinderNotFoundException(@NonNull Class<?> clazz) {
    super("Do you have registered {className}.class to the binder in the adapter/pool?"
        .replace("{className}", clazz.getCanonicalName()));
  }
```

**Comment by zyallday** [comment]
匿名内部类没有 canonicalName 用 clazz.getName() 更好

**Comment by drakeet** [comment]
MultiType 的最新源码中，使用的是 `clazz.name`:
```kotlin
internal class BinderNotFoundException(clazz: Class<*>) : RuntimeException(
  "Have you registered the ${clazz.name} type and its binder to the adapter or type list?"
)
```
因此这个 issue 本身是不成立的，即将关闭。
