### ISSUE TITLE
请问后续如何将数据传入ItemViewBinder

### ISSUE THREAD

**Issue by ghost** [drakeet/MultiType#273]
有一个场景是这样的，需要在 Activity 中监听 ViewPager 的滑动，当滑动的时候需要告诉 ItemViewBinder 里面的控件 ViewPager 正在滑动，我需要怎么将数据传入进去

**Comment by drakeet** [comment]
持有 `ItemViewBinder` 对象引用，通过其方法把数据传递给它即可。
