### ISSUE TITLE
Why is MultiTypeAdapter final?

### ISSUE THREAD

**Issue by ezamelczyk** [drakeet/MultiType#281]
As of 4.0.0-alpha2 `MultiTypeAdapter` is final. It's such a breaking change for my project that I may never update. Can I ask to remove this constraint or at least explain why it was added?

**Comment by drakeet** [comment]
It's open now:
https://github.com/drakeet/MultiType/blob/master/library/src/main/kotlin/com/drakeet/multitype/MultiTypeAdapter.kt#L31 
Try the alpha3, please.
