### ISSUE TITLE
recycleview 网格布局点击在展开一个网格布局

### ISSUE THREAD

**Issue by suziqiang** [drakeet/MultiType#285]
你好 这个框架能实现下面的需求 
联网请求list ClassBean 对象集合，每一个ClassBean对象里面又有一个list student 对象集合
我用网格布局展示classBean对象集合，一行展示3个item, 点击其中的一个item 向下展开 并用网格布局展示student对象集合，一行五个student item.

**Comment by drakeet** [comment]
使用 MultiType 可以实现的，但你需要自行实现它，这里不提供具体实现帮助。
