### ISSUE TITLE
已看已有的issues   notifyItemChanged  无效  只有在 滑动列表的时候才会生效

### ISSUE THREAD

**Issue by xyZangGit** [drakeet/MultiType#286]
数据源的数据bean确实改变了
![image](https://user-images.githubusercontent.com/19574114/62993702-2f037c80-be8b-11e9-85ed-c9a83d015337.png)
只有从新调用setItems（List）
notifyDataSetChanged  才会生效

下面是我的adapter 注册截图
![image](https://user-images.githubusercontent.com/19574114/62997417-c6bc9700-be9a-11e9-83be-ce4b0c140fb2.png)

**Comment by drakeet** [comment]
抱歉，这不是 MultiType 的问题，换句话说，按照你的写法，如果使用原生 RecyclerView Adapter 照样会这样。MultiType 只是很薄的一层类型分发框架，它不会改变你的 RecyclerView 行为。

**Comment by xyZangGit** [comment]
> 抱歉，这不是 MultiType 的问题，换句话说，按照你的写法，如果使用原生 RecyclerView Adapter 照样会这样。MultiType 只是很薄的一层类型分发框架，它不会改变你的 RecyclerView 行为。

不是这样的，大大，如果我不使用MultiTypeadapter，使用原生的adapter，我调用replaceItem是可以生效的，已经尝试过了，我现在只能从新resetdata

**Comment by drakeet** [comment]
@xyZangGit 如果你怀疑是 MultiType 的问题，你可以在此提供一个最小相关性可复现程序工程，然后我们才能够排查和确定问题。

**Comment by SuperXpher** [comment]
我也遇到了这个问题，请问您解决了吗？

**Comment by drakeet** [comment]
如果你坚持认为这是 MultiType 的问题，请提供最小可复现程序，谢谢！

**Comment by drakeet** [comment]
@SuperXpher @xyZangGit 两位都坚持认为这个事情和 MultiType 有关，因此现在重新 reopen 这个 issue，我将补全相关测试。也请你们请提供复现程序，最终如果确认是 MultiType 的问题，我将立即修复它。谢谢！

**Comment by drakeet** [comment]
我这边尝试了一番，都**无法复现**这个事情，晚些时候将发起 PR 补充相关单元测试。

**Comment by xyZangGit** [comment]
非常感谢群主的开源和细心解答，时间过得比较久了，但是当时确实是更新没有反应的，可以让 另外一位老哥 提供一个demo，我当时只能调用notify  刷新全部解决这个问题

**Comment by SuperXpher** [comment]
@drakeet 首先谢谢您的回复，不过很遗憾，我也无法复现，出现的概率很小，甚至没有发现任何规律。我现在也是通过全部刷新解决这个问题。

**Comment by SuperXpher** [comment]
@xyZangGit 我想问一下您当时的项目中是否有用Fragmentation这个框架

**Comment by drakeet** [comment]
MultiType 只是很薄的一层类型分发层，理论上这个问题不可能发生。因为现在无法复现和验证它，所以这个 issue 将关闭。

**Comment by appdev** [comment]
@SuperXpher @xyZangGit 两位有什么其他的解决办法吗？现在也遇到这个问题。具体是更新了 数据，但是UI没有更新，这个时候如果稍微滑动一下列表，UI就更新了，不知道是不是 MultiType 有关，只有快速调用 `notifyItemChanged` 的时候会不起效果。如果间隔一段时间调用就没有这个问题
