### ISSUE TITLE
如何每个ItemViewBinder传参？

### ISSUE THREAD

**Issue by zhengshiteng** [drakeet/MultiType#298]
有些时候需要在构造器或者onCreateViewHolder中就需要拿到当前item的数据，这时候又拿不到positon，而ItemBinder的创建外部又不可控制无法通过构造器传值。

**Comment by drakeet** [comment]
onCreateViewHolder 的时候无法知道当前位置，无法获取 position，就算你用原生 Adapter 也是如此，因此 MultiType 同样无法提供这样的内容。
