### ISSUE TITLE
瀑布流布局上下滚动列表界面闪烁

### ISSUE THREAD

**Issue by wangzhiyuan** [drakeet/MultiType#299]
实现瀑布流布局上下滚动列表界面闪烁而且还会串位，原因是getItemid不唯一，且这个方法不可重写
详见：https://medium.com/@hanru.yeh/recyclerviews-views-are-blinking-when-notifydatasetchanged-c7b76d5149a2

**Comment by drakeet** [comment]
MultiType 支持覆写 `getItemId()`，而且「瀑布流布局上下滚动列表界面闪烁」这个问题和 MultiType 本身无关，这属于 RecyclerView 或其 LayoutManager 的问题。因此这个 issue 将被关闭。
