### ISSUE TITLE
支持嵌套RV吗

### ISSUE THREAD

**Issue by jungletian** [drakeet/MultiType#3]
RT

**Comment by drakeet** [comment]
支持，无论 item 要怎么样都支持，只要按照两个步骤，实现 RecyclerContent & RecyclerViewItemProvider 即可

**Comment by drakeet** [comment]
所以使用了这个库以后，要实现类似 Google Play 或 App Store 应用首页那种复杂的列表视图，将非常容易，按部就班，毫无压力。

**Comment by jungletian** [comment]
👍
