### ISSUE TITLE
Proguard for registered class

### ISSUE THREAD

**Issue by huynguyennovem** [drakeet/MultiType#301]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/MultiType

 - [x ] Bug report. If you’ve found a bug, spend the time to write a failing test. Please provide 
       your device name, device OS version, and describe the reproduction steps.

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

###### Info:

 - MultiType version: 4.2.0
 - Device OS version: Android 6.0
 - Device Name: Nexus 5

###### Description: 
The problem came when set **minifyEnabled true** and **shrinkResources true** for **buildTypes** in app gradle. The data can not parse and display as null.

###### Reproduction Steps: 
1. Set in app gradle:
```gradle
buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
}
```
2. Set in _proguard-rules.pro_ for keeping Gson parse entity class
```pro
-keep class com.example.entity.response.** { *; }
```
3. Build release apk and the result is empty data when display

###### My thoughts: 
After trying, I saw that I have not kept adapter class which uses in multi type adapter.

###### What did I do: 
Modify _proguard-rules.pro_:
```pro
-keep class com.example.entity.response.** { *; }
-keep class com.example.entity.adapter.** { *; }
```

Then, it worked!

**Comment by drakeet** [comment]
This is not a problem or scope of MultiType.
