### ISSUE TITLE
com.drakeet.multitype.DelegateNotFoundException: Have you registered the java.lang.Integer type and its delegate or binder?

### ISSUE THREAD

**Issue by shouzhong** [drakeet/MultiType#302]
kt写的代码
版本：4.2.0
注册代码：register(Int::class, xxx)

**Comment by shouzhong** [comment]
> 
> 
> kt写的代码
> 版本：4.2.0
> 注册代码：register(Int::class, xxx)

java没这个问题

**Comment by wyntonchin** [comment]
kotlin中貌似Integer 和Int是俩东西

**Comment by agentchen** [comment]
> kt写的代码
> 版本：4.2.0
> 注册代码：register(Int::class, xxx)

register(Int::class.java, xxx)

**Comment by BugRui** [comment]
我都是Integer::class

**Comment by drakeet** [comment]
下一版已支持，感谢反馈！
