### ISSUE TITLE
使用的最新的4.2版本，scrollToPosition不起作用，不知道是我用的不对还是multitype的bug

### ISSUE THREAD

**Issue by wyntonchin** [drakeet/MultiType#305]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/MultiType

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Please provide 
       your device name, device OS version, and describe the reproduction steps.

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

###### Info:

 - MultiType version: 
 - Device OS version: 
 - Device Name:

**Comment by wyntonchin** [comment]
kotlin+androidx使用的multitype4.2 最新版

**Comment by drakeet** [comment]
无法复现，而且很大概率是你代码的问题。请换成传统 RecyclerView Adapter 实现试试，或者提供最小相关性可复现程序。

**Comment by wyntonchin** [comment]
thanks ，后来换成使用layoutmanager调用scroll没问题
