### ISSUE TITLE
MultiTypeAdapter调用notifyDataSetChanged()

### ISSUE THREAD

**Issue by ToweR10** [drakeet/MultiType#307]
MultiTypeAdapter调用notifyDataSetChanged()时会刷新所有级别的列表，这样不科学啊

**Comment by drakeet** [comment]
不明白你的具体意思，不过很明显这应该是 RecyclerView 的范畴，换句话说，就算你不使用 MultiTypeAdapter 而使用原生的 RecyclerView Adapter，行为和结果也是完成一样的，因为本来 MultiTypeAdapter 就算很轻薄的一层类型分发层，它并不会干扰或修改你的 notify 行为。
