### ISSUE TITLE
请问，如何结合JetPack的Paging库使用呀？

### ISSUE THREAD

**Issue by wjlight** [drakeet/MultiType#313]
我尝试加入Paging库结合MultiTypeAdapter，发现Paging库行为很异常，如果只是有普通的Adpater，Paging行为正常，请问有推荐的做法么？或者有其他的分页库推荐么？

**Comment by drakeet** [comment]
当你需要 Paging 的时候就去用 Paging，当你需要用 MultiTypeAdapter 的时候就用 MultiTypeAdapter。引入 MultiTypeAdapter 并不代表什么事情都必须使用 MultiTypeAdapter 来完成。另外，Paging 更多是用来适配单一类型的数据，因此也没必要使用 MultiTypeAdapter。
