### ISSUE TITLE
收起功能和子项背景该如何做呢？

### ISSUE THREAD

**Issue by qwer2y** [drakeet/MultiType#314]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/MultiType

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Please provide 
       your device name, device OS version, and describe the reproduction steps.

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

###### Description: 

1、但是我的需求是有展开和收起功能，展开类似抖音但是抖音没有收起，该如何做呢
2、第二个type共用一个背景图该如何实现呢？二级评论有一个背景图
![WechatIMG15](https://user-images.githubusercontent.com/25814380/100182805-72ff8100-2f18-11eb-82ad-bab721f8f41a.jpeg)

比如红圈部分共用一个背景

求解惑

**Comment by drakeet** [comment]
list.addAll，然后 notify adapter 刷新页面即可。这很容易，但这里不是提供业务需求实现方案的，您需要自行动脑筋。
