### ISSUE TITLE
使用OneToMany问题

### ISSUE THREAD

**Issue by prience03** [drakeet/MultiType#320]
drakeet，您好：
因使用me.drakeet.multitype:multitype:3.4.4版本多布局，列表中有多个相同的ItemViewBinder，里面嵌套使用RV， 下拉刷新后，
调用onBindViewHolder后，相同布局数据错乱，下面的数据跑到上面显示了。
ItemViewBinder上设置adapter部分代码，希望您能百忙之中看一下
![image](https://user-images.githubusercontent.com/7941649/115990128-4305f800-a5f4-11eb-9763-f723804d91ad.png)

**Comment by drakeet** [comment]
抱歉，从你的图片中看不出相关问题及其原因，请提供最小可复现程序。在此之前，我将关闭这个 issue。
