### ISSUE TITLE
我该如何在 ItemViewDelegate 中操作 items ？

### ISSUE THREAD

**Issue by RDSunhy** [drakeet/MultiType#321]
类似于QQ音乐app这个模块，recyclerview嵌套，切换tab 下面的横向recyclerview的数据更新。
想的是给tablayout 设置点击时间 修改 adapter.items 但是我在 ItemViewDelegate 里操作数据 调用 notifyXXX() 不起作用。
另外：想请教一下 这种布局 用 tablayout + recyclerview 实现 合适吗？
![image](https://user-images.githubusercontent.com/44076669/116647622-92aa4200-a9ad-11eb-85fa-447d9a8f5b42.png)

**Comment by drakeet** [comment]
> 但是我在 ItemViewDelegate 里操作数据 调用 notifyXXX() 不起作用。

能否提供能够复现此情况的示例程序？

**Comment by drakeet** [comment]
由于没有回复，将关闭这个 issue，如果有后续进展，再 reopen。
