### ISSUE TITLE
大家好，我使用MultiTypeAdapter的时候itme复用是数据混乱了，请问有人遇到吗？

### ISSUE THREAD

**Issue by 13760661144** [drakeet/MultiType#322]

**Comment by drakeet** [comment]
没有遇到过，而且历史上也没有反馈过类似问题，原理是也不可能存在这个问题（MultiType 只是薄薄的一层类型分发层，它只接收 Kotlin 中的 List 对象，在 Kotlin 中 List 是无法修改的，只有 MutableList 才能修改，所以 MultiType 不可能修改你的数据源）。

如果你要证明你说的情况和结论，请提供最小可复现程序，不然仅仅这么说，神仙都猜不到怎么回事，也无法帮助你。

**Comment by drakeet** [comment]
没有回复，关闭。
