### ISSUE TITLE
release模式下，混淆失败

### ISSUE THREAD

**Issue by liyqxtu** [drakeet/MultiType#323]
com.android.tools.r8.errors.b: Unexpected attempt to get register for a value without a register in method `com.xx.xx.adapter.SendImageDelegate$ViewHolder com.xx.xx.adapter.SendImageDelegate.onCreateViewHolder(android.content.Context)`.

**Comment by liyqxtu** [comment]
同样的代码，在Debug模式下，打包正常

**Comment by drakeet** [comment]
这不属于这个项目的问题
