### ISSUE TITLE
我正在开发OpenHarmony应用，使用JS语言，你们能否支持JS版本？我愿意参与开发，期待回复。

### ISSUE THREAD

**Issue by YanQiu12** [drakeet/MultiType#335]
我正在开发OpenHarmony应用，使用JS语言，你们能否支持JS版本？我愿意参与开发，期待回复。

**Comment by 530l** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by drakeet** [comment]
请您自行开发。
