### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by zhoujianhanyu** [drakeet/MultiType#35]
很好的设计，感谢分享！建议在onBindViewHolder的方法里加上position这个参数吧

**Comment by drakeet** [comment]
建议你看看 wiki，不推荐把 position 传入 provider 层面，如果需要，请继承 MultiTypeAdapter 进行拓展而不是去修改源码。

**Comment by drakeet** [comment]
wiki 中详细说明了这类问题：https://github.com/drakeet/Effective-MultiType/blob/master/README.md
