### ISSUE TITLE
can't support fresco

### ISSUE THREAD

**Issue by Lee-Wang-Jing** [drakeet/MultiType#37]
sample‘’s Imageview replace SimpleDraweeView run project has wrong

**Comment by drakeet** [comment]
This does not matter with MultiType. You should find your real log or reason.

**Comment by drakeet** [comment]
按照你说的步骤，我运行起来了，完全没有问题。
你是不是忘记初始化 Fresco 了？需要在应用调用 `setContentView()` 之前，进行初始化：

`Fresco.initialize(context);`

**Comment by drakeet** [comment]
![image](https://cloud.githubusercontent.com/assets/5214214/20421685/879a7afa-ada0-11e6-8ef8-55ac5bd64a95.png)
![image](https://cloud.githubusercontent.com/assets/5214214/20421695/950d7642-ada0-11e6-8d1b-2d6fa97505a6.png)
![image](https://cloud.githubusercontent.com/assets/5214214/20421702/a1ac7542-ada0-11e6-9b14-a3dccc731323.png)

和 Fresco 一起使用完全没有问题，而且本来也不应该有问题。MultiType 不可能去影响 Views 的内容，它只是非常轻薄的一层，更多详情可以看我写的详解文章：

https://drakeet.me/effective-multitype
