### ISSUE TITLE
recyclerview嵌套里面的recyclerview不给高度显示不出来的问题，有没有人解决了

### ISSUE THREAD

**Issue by dante312** [drakeet/MultiType#39]

**Comment by drakeet** [comment]
请参考我的示例，这不属于 MultiType 的范畴，MultiType 不会改变 RecyclerView 的行为。

**Comment by dante312** [comment]
谢谢，因为说明里写了支持嵌套，这个问题不解决，嵌套的意义就降低很多

**Comment by drakeet** [comment]
这个现象和有没有使用 MultiType 是没关系的，也就是说，就算你不使用 MultiType，表现也是一样的，MultiType 只做类型分发，绝不会去影响 Item View 内容。

**Comment by dante312** [comment]
好的，谢谢大神的耐心回复

**Comment by drakeet** [comment]
嗯，你可以看看我那个 Bilibili 示例，能不能自动计算高度，我记不清了，但仍然是那句话，MultiType 不应该管这件事，它属于 RV 本身的规则和设定。
