### ISSUE TITLE
May use Delegate naming instead of Provider is more appropriate?

### ISSUE THREAD

**Issue by drakeet** [drakeet/MultiType#4]
Maybe...

**Comment by dev4mobile** [comment]
。。。

**Comment by drakeet** [comment]
@dev4mobile What's wrong with you?

**Comment by dev4mobile** [comment]
不要用静态变量 

```
private static ArrayList<Class<? extends ItemContent>> contents = new ArrayList<>();
private static ArrayList<ItemViewProvider> providers = new ArrayList<>();
```

**Comment by dev4mobile** [comment]
还有 如果需求要加一个footer， 得在最后加一个假的footer类型的TypeItem，能否加个开关设置 来对付 包含footer 和 header 这种需求

**Comment by drakeet** [comment]
@dev4mobile 对于 header or footer 的需求，使用 Multi Type 是很容易做到的，我不做过多定制，对于 library 我是非常克制的。如果你不懂，我晚上可以在 sample 中写个示例。

至于 Pool 要不要静态的问题，我在其他 issue 回复过，那是要不要全局类型池的问题，你不能直接说不要 static，那只能显示你还是个门外汉，抱歉！

更多关于这个问题的回答：https://github.com/drakeet/MultiType/blob/master/README.md#qa-english-version-later

另外，有问题请开新 issues，这里讨论的是题主问题。
