### ISSUE TITLE
有个item包含的是gridview样式 我要分别点击执行不同的时间逻辑 怎么搞

### ISSUE THREAD

**Issue by hxingever** [drakeet/MultiType#41]
有个item包含的是gridview样式 我要分别点击gridview中的item执行不同的事件逻辑 怎么搞 ？？
除了extends MultyTypeAdapter 加个setOnItemClickListener方法可以实现之外 还有其他更好的方式吗
一般的事件都是可以在ItemViewProvider中实现
![qq 20161203100834](https://cloud.githubusercontent.com/assets/9794894/20856042/533ed3da-b941-11e6-8525-4f16097aac62.png)
 但是如果像gridview这种我要分别点击执行不同的时间逻辑还有更好的方法么？![image](https://cloud.githubusercontent.com/assets/9794894/20856004/657e664c-b940-11e6-8bf2-57035c4e6e17.png)

**Comment by drakeet** [comment]
这是很容易的事情，在 Item View Provider 内部进行即可，或者你也可以由 Provider 提供出接口方法。详情见我的详解文章：https://drakeet.me/effective-multitype
