### ISSUE TITLE
Recyclerview 添加头部

### ISSUE THREAD

**Issue by cheng1992zhen** [drakeet/MultiType#42]
Recyclerview添加头部需要使用自定义的RecyclerView.Adapter,怎么使用MultiType呢?

**Comment by drakeet** [comment]
请参考我的详解文章：https://github.com/drakeet/Effective-MultiType

具体相关内容：

https://github.com/drakeet/Effective-MultiType/blob/master/README.md#multitype-%E4%B8%8E%E4%B8%8B%E6%8B%89%E5%88%B7%E6%96%B0%E5%8A%A0%E8%BD%BD%E6%9B%B4%E5%A4%9Aheaderviewfooterviewdiff

**Comment by cheng1992zhen** [comment]
看到了解决方法,自己看的不仔细,脸红...

**Comment by drakeet** [comment]
: ) MultiType 对于添加 HeaderView 还是非常容易的。
