### ISSUE TITLE
希望楼主提供一个完善的自动加载更多的功能

### ISSUE THREAD

**Issue by ruhaly** [drakeet/MultiType#46]
希望楼主提供一个完善的自动加载更多的功能，毕竟这个功能是跟adapter紧密联系的，

**Comment by drakeet** [comment]
对不起，MultiType 不会提供这个功能，原因请参见 wiki.

**Comment by drakeet** [comment]
我会给个完整的示例，但不会在 MultiType 内部侵入来实现这个功能，因为它不属于 TYPE 的范畴，应该在 MultiType 外部实现，而且实现很容易的。

**Comment by ruhaly** [comment]
要完善的还是有不少代码的，是不是可以实现一个跟弘扬的https://github.com/hongyangAndroid/baseAdapter这个一样的wrapadapter包裹着你的这个adapter ，这个完全解耦了，但是弘扬的那个有不少问题而且不不完善，现在也不维护了

**Comment by drakeet** [comment]
可以提供一个继承 MultiTypeAdapter 的 Adapter 来实现封装。#TODO

**Comment by ruhaly** [comment]
期待楼主

**Comment by ruhaly** [comment]
如果可以的话，最好不要依赖MultiTypeAdapter ，完全解耦

**Comment by drakeet** [comment]
已开源由 rebase-android 实现的完全解耦的 SwipeRefreshDelegate 和 LoadMoreDelegate: https://github.com/drakeet/rebase-android/blob/master/app/src/main/java/com/drakeet/rebase/fragment/ListBaseFragment.java#L49-L50

**Comment by ruhaly** [comment]
谢谢，没想到楼猪这么长时间了还放心上，给个赞

**Comment by kandra777** [comment]
楼主您好 我目前的布局是 1个竖的recyclerview嵌套2个横的recyclerview和一个竖的recyclerview,我想知道要实现这个嵌套的竖的recyclerview的加载更多应该如何实现啊?

**Comment by drakeet** [comment]
@kandra777 你的问题与 MultiType 完全无关，在此不做详细解答。简单说就是，内嵌竖直 RV 应该考虑高度使用 wrap content，然后该怎么加载更多就怎么加载更多，嵌套不嵌套都一样。你把它当成一个非内嵌 RV 去给它加载更多就行了。
