### ISSUE TITLE
itemProvider中绑定数据的疑问

### ISSUE THREAD

**Issue by Dragon-Boat** [drakeet/MultiType#50]
itemProvider中，onBindViewHolder中提供了当前viewholder和相关的数据类，但是我想访问上一个位置的数据，应该如何做？ 问题抽象一下，就是当前item的不仅和自身状态有关，也和上一个item的数据有联系。

**Comment by drakeet** [comment]
那你可以把 items List 通过 provider 构造函数或 setter 方法传给 provider 即可，provider 中可以拿到 position，再调用例如 items.get(getPosition() - 1)
