### ISSUE TITLE
MuliTypeAdapter 实现 TypePool 接口的问题

### ISSUE THREAD

**Issue by Dragon-Boat** [drakeet/MultiType#51]
看源码中，MuliTypeAdapter中，已经通过构造器拥有了TypePool接口的对象，为什么本身还需要实现这个接口？是有额外的扩展性考虑吗？

**Comment by drakeet** [comment]
MuliTypeAdapter 实现了 TypePool，也就是说它本身是一个 TypePool，构造器中的 pool 只是提供一个给 MultiType init with all item types from another type pool 的渠道。

**Comment by drakeet** [comment]
就像 ArrayList 也提供了 ArrayList(Collection list) 构造函数。
