### ISSUE TITLE
assertAllRegistered()  调用过时方法

### ISSUE THREAD

**Issue by zhangls2014** [drakeet/MultiType#52]
由于 onFlattenClass(Object item) 方法过时，于是实现了MultiTypeAdapter.setFlatTypeAdapterMultiTypeAdapter()  方法，在程序运行时 crash 掉了，日志显示 assertAllRegistered()  方法下 adapter.indexOf(adapter.onFlattenClass(item));  出错，因为onFlattenClass(item) 过时，未实现。
望改善，祝好！

**Comment by drakeet** [comment]
感谢反馈，今晚将会更正。

**Comment by drakeet** [comment]
已经修复，今晚将会发布到 maven central 和 jcenter.

**Comment by drakeet** [comment]
已经发布到 maven: https://github.com/drakeet/MultiType/commit/211069cebee73032c67ffe55c6e0597034234c22
