### ISSUE TITLE
可以在 Activity 中进行 Diff，或者继承 MultiTypeAdapter 提供接收数据方法，在方法中进行 Diff.

### ISSUE THREAD

**Issue by zhengjieAdriod** [drakeet/MultiType#56]
大神，这个具体怎么做啊？
我是想把他这个diff的功能，与MutiType一起用的。搞了快一天了还是搞不定啊，一直不走三个参数的onBindViewHolder（）；

希望大神给指点指点，最好有个小demo/  万分感谢...

**Comment by drakeet** [comment]
请把你的代码和使用的 MultiType 版本号贴出来，并描述清楚问题，我可以帮你看看。

**Comment by zhengjieAdriod** [comment]
https://github.com/mcxtzhang/SupportDemos  我看了他这个文章之后，就在他的demo中添加MultiType 的功能。意思就是：在他这个单一的itemtype中新添加一个itemtype, 并使用他demo中的diff功能。 实现的过程中，需要用到三个参数的onBindViewHolder（）；问题就是这个方法，应该在哪里复写？我是在MultiTypeAdapter的子类中复写的。

**Comment by frankfancode** [comment]
我也在做类似的功能，把 数据存储到 ViewHolder 中，在 onBindViewHolder 时 比较一下 ViewHolder 里面保存的数据 和 item 里面传入的数据，如果相同就不刷新了。
我觉得这个diff 的功能还是比较常用的，尤其是用这个库的会有很多不同的item，估计会有很多复杂的 item，重复刷新可能滑动会比较卡。

**Comment by zhengjieAdriod** [comment]
@frankfancode 请问你是在哪里复写这个三个参数的onBindViewHolder （）方法的？？

**Comment by drakeet** [comment]
如果是为了 diff，不应该覆写 onBindViewHolder，onBindViewHolder 是用于绑定数据的而不是让人来做数据筛选或处理的。

**Comment by drakeet** [comment]
其实我这句话已经说得非常清楚了，不理解的话你可以读 24 遍后再想想：
> 可以在 Activity 中进行 Diff，或者继承 MultiTypeAdapter 提供接收数据方法，在方法中进行 Diff. 

若 24 遍后还不理解，待会儿我给你写个示例。

**Comment by zhengjieAdriod** [comment]
这篇文章我在这儿看了两天了，只是会用了，还是不能通过他的灵活性进行功能添加。我再想想..

**Comment by zhengjieAdriod** [comment]
@drakeet 文章里所说的diff 就是v7包下的DiffUtil吗？

**Comment by drakeet** [comment]
@zhengjieAdriod 没有限定，可以是 v7 DiffUtil，也可以是其他 DiffUtil 或你自己造的 DiffUtil，文章里说了，这不属于 MultiType 的范畴，MultiType 不会去管你的数据 diff，只接受数据，这个数据可以是全量数据，也可以是你 diff 后的数据。

**Comment by drakeet** [comment]
不知道那句话你 24 遍读完了没，刚简单写了下所谓 "在 Activity 中进行 Diff" 的示例，代码如下：

```java
public class FlexActivity extends AppCompatActivity {

    List<X> oldItems;
    MultiTypeAdapter adapter;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_flex);
        /* Init your oldItems, adapter and recyclerView ... */
        /* Fetch your data from server and call onLoadData */
    }


    void onLoadData(List<X> newItems) {
        final XDiffCallback diffCallback = new XDiffCallback(oldItems, newItems);
        final DiffUtil.DiffResult diffResult = DiffUtil.calculateDiff(diffCallback);

        this.oldItems.clear();
        this.oldItems.addAll(newItems);
        diffResult.dispatchUpdatesTo(adapter);
    }


    static class X {
        int id;
    }


    static class XDiffCallback extends DiffUtil.Callback {

        private final List<X> oldList;
        private final List<X> newList;


        XDiffCallback(List<X> oldList, List<X> newList) {
            this.oldList = oldList;
            this.newList = newList;
        }


        @Override
        public int getOldListSize() {
            return oldList.size();
        }


        @Override
        public int getNewListSize() {
            return newList.size();
        }


        @Override
        public boolean areItemsTheSame(int oldItemPosition, int newItemPosition) {
            return oldList.get(oldItemPosition).id == newList.get(newItemPosition).id;
        }


        @Override
        public boolean areContentsTheSame(int oldItemPosition, int newItemPosition) {
            final X oldItem = oldList.get(oldItemPosition);
            final X newItem = newList.get(newItemPosition);
            return Objects.equals(oldItem, newItem);
        }
    }
}
```

看完这个代码后，你可以再读几遍那句话，看看是不是说得一点没错。

**Comment by zhengjieAdriod** [comment]
万分感谢！！

**Comment by drakeet** [comment]
又简单写了下，所谓 "继承 MultiTypeAdapter 提供接收数据方法，在方法中进行 Diff"：

```java
public class XDiffMultiTypeAdapter extends MultiTypeAdapter {

    private List<X> oldItems;


    public XDiffMultiTypeAdapter(@NonNull List<X> items) {
        super(items);
    }


    public void setItems(List<X> newItems) {
        final XDiffCallback diffCallback = new XDiffCallback(oldItems, newItems);
        final DiffUtil.DiffResult diffResult = DiffUtil.calculateDiff(diffCallback);

        this.oldItems.clear();
        this.oldItems.addAll(newItems);
        diffResult.dispatchUpdatesTo(this);
    }


    static class XDiffCallback extends DiffUtil.Callback {

        private final List<X> oldList;
        private final List<X> newList;


        XDiffCallback(List<X> oldList, List<X> newList) {
            this.oldList = oldList;
            this.newList = newList;
        }


        @Override
        public int getOldListSize() {
            return oldList.size();
        }


        @Override
        public int getNewListSize() {
            return newList.size();
        }


        @Override
        public boolean areItemsTheSame(int oldItemPosition, int newItemPosition) {
            return oldList.get(oldItemPosition).id == newList.get(newItemPosition).id;
        }


        @Override
        public boolean areContentsTheSame(int oldItemPosition, int newItemPosition) {
            final X oldItem = oldList.get(oldItemPosition);
            final X newItem = newList.get(newItemPosition);
            return Objects.equals(oldItem, newItem);
        }
    }
}
```

好了，我已经双方面用代码解释了 "可以在 Activity 中进行 Diff，或者继承 MultiTypeAdapter 提供接收数据方法，在方法中进行 Diff. " 这句话，最后有没有发现我这句话已经非常言简意赅。

注意：如果你要容纳多种 item types，应该使用 `?` 替代我这里的 `X`.

**Comment by zhengjieAdriod** [comment]
确实非常言简意赅，对我这个新手不好理解。真是有幸膜拜到大神的代码。

XDiffCallback 并没有重写 public Object getChangePayload(int oldItemPosition, int newItemPosition) ；
该方法, 返回 一个 代表着新老item的改变内容的 payload对象。 该对象会在三个参数的onBindViewHolder （）中使用。以达到只改变item上的部分数据。

**Comment by drakeet** [comment]
@zhengjieAdriod 不客气 ^ ^
`getChangePayload` 这个方法你可以自行根据你的需要进行覆写。

**Comment by drakeet** [comment]
@frankfancode

**Comment by zhengjieAdriod** [comment]
例如哪些需要啊？

**Comment by drakeet** [comment]
这方法的字面意思是：一个 item 中，具体是哪些字段数据产生了变化。
它被调用的时机是：`areItemsTheSame()` 返回 `true` 而 `areContentsTheSame()` 返回 `false`. 
> When areItemsTheSame(int, int) returns true for two items and areContentsTheSame(int, int) returns false for them, DiffUtil calls this method to get a payload about the change.

另外，这个方法可以不覆写，它的返回值是 `@Nullable`.

**Comment by drakeet** [comment]
这已经不属于 MultiType 的范畴了，具体内容你应该自行学习使用。经过一番努力后实在不懂，我可以再帮忙看看。

**Comment by drakeet** [comment]
如果你想学习这个方法，我可以给你提供一篇非常好且详尽的文章：

https://medium.com/@nullthemall/diffutil-is-a-must-797502bc1149#.l3a13i5sq

**Comment by zhengjieAdriod** [comment]
好的, 感谢大神！

**Comment by zhengjieAdriod** [comment]
`大神，public boolean areItemsTheSame(int oldItemPosition, int newItemPosition)方法中要做类型判断吗？拿不到id这个字段的
class DiffCallBack02<T> extends DiffUtil.Callback {

    private final List<T> oldList;
    private final List<T> newList;


    DiffCallBack02(List<T> oldList, List<T> newList) {
        this.oldList = oldList;
        this.newList = newList;
    }


    @Override
    public int getOldListSize() {
        return oldList.size();
    }


    @Override
    public int getNewListSize() {
        return newList.size();
    }


    @Override
    public boolean areItemsTheSame(int oldItemPosition, int newItemPosition) {
        T oldT = oldList.get(oldItemPosition);
        T newT = newList.get(newItemPosition);
        //这块要做bean类型的判断吗？？
        return oldList.get(oldItemPosition).id == newList.get(newItemPosition).id;
    }


    @Override
    public boolean areContentsTheSame(int oldItemPosition, int newItemPosition) {
        final T oldItem = oldList.get(oldItemPosition);
        final T newItem = newList.get(newItemPosition);
        return Objects.equals(oldItem, newItem);
    }
}`

**Comment by frankfancode** [comment]
@drakeet 收到，相当赞

**Comment by drakeet** [comment]
@zhengjieAdriod 我不是大神。diff callback 中 id 不是必须的，你自己思考，我不能一直手把手告诉你每一步应该怎么做。

**Comment by zhangle1** [comment]
刚想问的问题 发现有好多小伙伴多问了0.0

**Comment by anson39f** [comment]
@drakeet 找不到这个网址：https://medium.com/@nullthemall/diffutil-is-a-must-797502bc1149#.l3a13i5sq

**Comment by drakeet** [comment]
@anson39f 我这边是可以打开的，如果打不开，你需要科学上网。
