### ISSUE TITLE
getPosition() 方法不能获得正确的 Position

### ISSUE THREAD

**Issue by zhangls2014** [drakeet/MultiType#57]
Q: 如何在 ItemViewProvider 中获取到 item position？  A: 从 v2.3.0 版本开始，只需要在你的 ItemViewProvider 子类里调用 getPosition() 方法即可。如果低于 v2.3.0 版本，可以调用 holder.getAdapterPosition() 获得同样结果。
在我使用 v2.3.4 时发现，他们俩并不一致
onClick: ===AdapterPosition:0===Position:1
onClick: ===AdapterPosition:1===Position:1
onClick: ===AdapterPosition:2===Position:2
onClick: ===AdapterPosition:3===Position:3
onClick: ===AdapterPosition:4===Position:4
onClick: ===AdapterPosition:5===Position:5
onClick: ===AdapterPosition:0===Position:0
onClick: ===AdapterPosition:1===Position:0
onClick: ===AdapterPosition:2===Position:0
onClick: ===AdapterPosition:2===Position:0
onClick: ===AdapterPosition:3===Position:3
onClick: ===AdapterPosition:3===Position:3
onClick: ===AdapterPosition:21===Position:22
onClick: ===AdapterPosition:22===Position:22
onClick: ===AdapterPosition:22===Position:22
onClick: ===AdapterPosition:23===Position:24
onClick: ===AdapterPosition:23===Position:24
这是我随手打印的日志

**Comment by drakeet** [comment]
请贴出你的相关代码。

**Comment by zhangls2014** [comment]
https://github.com/zhangls2014/Weibo/blob/master/app/src/main/java/cn/zhangls/android/weibo/ui/home/weibo/WeiboFrameProvider.java
哥，是不是这么用的，给点意见

**Comment by drakeet** [comment]
感谢反馈，这确实是一个 BUG！getPosition() 如果没有马上消费，确实会存在被新的 item 绑定上新的位置导致旧的 item view provider getPosition() 不正常。建议先用 holder.getAdapterPosition() 替代，抱歉！

**Comment by drakeet** [comment]
已经修复和发布更新：https://github.com/drakeet/MultiType/releases/tag/v2.3.5

**Comment by cheng1992zhen** [comment]
我在多次滑动列表后,holder.getAdapterPosition()会得到-1值,无法返回正确的Position,请问是什么原因?
 java.lang.ArrayIndexOutOfBoundsException: length=18; index=-2

**Comment by drakeet** [comment]
@cheng1992zhen 你使用的 RecyclerView 是哪个版本？我不知道你怎么做的，这看起来属于 RecyclerView 的问题，如果要我帮忙解答，请给我发邮件并尽可能描述清楚你的状况，必要的时候提供源代码。请勿在这个 issue 下讨论太多与主题无关的内容。

**Comment by drakeet** [comment]
@cheng1992zhen 关于 RecyclerView 的这个问题，我猜你很可能使用了 item 动画和局部刷新，我曾经写过一篇解决这个问题的文章：[《RecyclerView Bug：IndexOutOfBoundsException: Inconsistency detected. Invalid item position》](https://drakeet.me/recyclerview-bug-indexoutofboundsexception-inconsistency-detected-invalid-item-position-solution)，你可以看看，这应该不属于 MultiType，暂时不要在这儿讨论了。

**Comment by cheng1992zhen** [comment]
好的,谢谢你的解答,我再仔细观察一下.

**Comment by drakeet** [comment]
@cheng1992zhen 我今天也又遇到这个问题了，当数据量很大的时候，很容易触发，触发时机在于列表数据更新中，这时候用户滑动了列表，就会导致这个异常，它确实是完全属于 `RecyclerView` 的 BUG。好在我在一年半已经就已经知道它发生的原理和提出了完美解决办法，今天一试，仍然奏效，就是我上面提到的那篇文章：[《RecyclerView Bug：IndexOutOfBoundsException: Inconsistency detected. Invalid item position》](https://drakeet.me/recyclerview-bug-indexoutofboundsexception-inconsistency-detected-invalid-item-position-solution)

我的代码示例：
![image](https://cloud.githubusercontent.com/assets/5214214/21761899/ecf29ba8-d690-11e6-882f-e786f9349590.png)
