### ISSUE TITLE
添加依赖运行项目后报错

### ISSUE THREAD

**Issue by jasonfresher** [drakeet/MultiType#61]
你好，我按照步骤在build.gradle文件添加依赖运行项目报错，
_# Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/app/ActionBarDrawerToggleHoneycomb$SetIndicatorInfo;_
请问这个问题怎么解决？

**Comment by drakeet** [comment]
想必你们的 support libs 是 24 版以下，MultiType 引用了 25 版 RecyclerView，25 版会和 24 版以下产生冲突，所以，要么你们升级到 25，要么使用 wiki 中的方法，排除掉 MultiType 内部引用的 support libs.

**Comment by jasonfresher** [comment]
wiki中好像没有寻找到排除support libs的方法

**Comment by jasonfresher** [comment]
dependencies {
    compile('me.drakeet.multitype:multitype:2.3.5', {
       exclude group: 'com.android.support'
    })
    compile 'com.android.support:recyclerview-v7:你选择的版本'
}
不好意思 看到了

**Comment by drakeet** [comment]
对了，顺便说一下，wiki 中没有还没更新到最新 2.4.0 版本，建议直接使用 MultiType 2.4.0 版本.

**Comment by jasonfresher** [comment]
好的，非常感谢
