### ISSUE TITLE
关于 二级 ViewProvider 示例疑问

### ISSUE THREAD

**Issue by ThatRoy** [drakeet/MultiType#63]
你好，我在使用 版本号为 2.4.1 过程中，遇到一个问题，想请教下。

使用场景：
对于聊天消息，每种消息都有左右样式，但左右样式的数据绑定操作是一样，因此想说继承 
ItemViewProvider ，重写 onCreateViewHolder() 方法，然后在这里根据数据对象的类型（发送或接受消息）来加载左或右布局，onBindViewHolder() 方法则进行相同的数据绑定操作。

问题：
在 onCreateViewHolder() 方法获取不到当前位置对应的数据对象，无法进行判断

其他：
1.看了 TimeMachine 的消息列表实现，看到左右消息区分了不同的 Content ，Provider ，但是数据内容，数据绑定是一样，这样实现会不会冗余?

2.在 "https://gank.io/post/5823bcf6421aa90e799ec2ad" 中，看到这句"每一种消息都有左边和右边的样式，分别对应别人发来的消息和你发出的消息。如果左边算一种，右边又算一种，就是比较不好的设计了，会导致布局内容重复、冗余，修改操作都要做两遍。最好的方案是让他们视被为同一种类型，然后在 item 框层次进行左右边判断和框架相关数据绑定。"
这里的 item 框层次进行左右判断，是指?

可能是哪里愚钝，没有理解，希望指点，谢谢~~

**Comment by ThatRoy** [comment]
后面稍微想了下，按照 MultiType 中的 WeiboAdapter 的写法，是根据 Weibo 对象的 content 对象类型，去实现二级 Provider ，但是这个 Content 对象还要根据自己是发送或接受的类型，再去对应不同的 Provider，这算是三级 Provider ？

**Comment by drakeet** [comment]
请参考 wiki 进行，TimeMachine 由于精力有限，当时并没有采用 wiki 中建议的设计而是简单分为两种消息类型。
另外，建议你看看我的 weibo sample，这是一个符合你需求的二级架构示例。

**Comment by drakeet** [comment]
我最近比较忙，暂无法提供详细示例。待我有空时候把 TimeMachine 调整成左右同一种消息类型，实际上很简单的，到时通知你。

**Comment by drakeet** [comment]
如何实在没有灵感，建议你好好理解下 weibo sample，其实这个示例提供的思想足够了。

**Comment by drakeet** [comment]
Content 内部使用 Layout 属性调整其 child view 位置，不需要三级结构。

**Comment by ThatRoy** [comment]
我现在根据 weibo sample ，已实现消息列表的展示，目前是卡在左右布局这边，然后项目赶(当然这是我自己的事情)，所以才来麻烦~实在抱歉，很感谢回复。

我现在是有一个思路就是在 onBindViewHolder() 里进行数据绑定时，对对布局进行动态左右的调整，看上去好像有点麻烦，我先自己折腾。

“Content 内部使用 Layout 属性调整其 child view 位置”，应该跟这个差不多~

**Comment by drakeet** [comment]
嗯，差不多是这样，你自己先思考或自己尝试实现，之后我会写个关于此的示例。

**Comment by ThatRoy** [comment]
谢谢，期待示例~
刚研究下，动态调整 child view 位置，确实有点麻烦，再没想到，只能先切回普通 RecyclerView ，\(╯-╰)/ （怪自己了）

**Comment by drakeet** [comment]
TimeMachine 已实现左右 chat message item 合一了。

**Comment by bannerkun** [comment]
> TimeMachine 已实现左右 chat message item 合一了。

请求这个demo有链接吗？最近要实现聊天页面正在找这方面对框架。

**Comment by linzhengloser** [comment]
> > TimeMachine 已实现左右 chat message item 合一了。
> 
> 请求这个demo有链接吗？最近要实现聊天页面正在找这方面对框架。

你可以看看这个 #264。
