### ISSUE TITLE
假如在这个的基础上想实现一个类似顶部悬停的功能要怎么做？

### ISSUE THREAD

**Issue by shlockfan** [drakeet/MultiType#65]
类似通讯录的首字母悬停顶部的功能

**Comment by drakeet** [comment]
**这不属于 MultiType 的范畴，MultiType 的定位是类型池与类型分发系统。**

如果你要实现 `RecyclerView` item 悬停或 Toast 悬停，可以监听 `RecyclerView` 的滚动位置事件，并采用 `FrameLayout` 布局，在 `RecyclerView` 之上层进行悬停、移动、更新等等操作。

**Comment by manondidi** [comment]
> **这不属于 MultiType 的范畴，MultiType 的定位是类型池与类型分发系统。**
> 
> 如果你要实现 `RecyclerView` item 悬停或 Toast 悬停，可以监听 `RecyclerView` 的滚动位置事件，并采用 `FrameLayout` 布局，在 `RecyclerView` 之上层进行悬停、移动、更新等等操作。

在下拉刷新的时候 拖动的时候 要处理隐藏什么的 ,比较麻烦

**Comment by Khaos116** [comment]
Sticky顶部悬停
https://github.com/khaos116/ABase/blob/master/app/src/main/java/cc/abase/demo/component/sticky/StickyActivity.kt
Grid拖拽排序
https://github.com/khaos116/ABase/blob/master/app/src/main/java/cc/abase/demo/component/drag/DragActivity.kt
