### ISSUE TITLE
一点小想法

### ISSUE THREAD

**Issue by woniu0936** [drakeet/MultiType#68]
这两天看auto-value，他的一个特别好的地方是Extension API，这样就可以自己扩展类似于auto-value-gson，auto-value-parcel这样的功能了，如果MultiType也能做类似的支持，是不是能在保证纯粹性和灵活性的基础上避免一些重复造轮子的事呢？

**Comment by drakeet** [comment]
MultiType 本来就支持随意拓展和灵活运用。另外你这么说比较泛泛而谈，并不清楚你的目的。如果可以，欢迎发起 Pull Request.

**Comment by woniu0936** [comment]
@drakeet 我的意思是提供类似MultiType-loadmore之类的插件，把MultiType作为核心库，MultiType-loadmore作为可选的插件，需要使用时，插件单独compile，这样的话可能用的时候就能少造一些轮子了。

**Comment by drakeet** [comment]
关于 LoadMore，wiki 中写得很清楚。MultiType 不会去实现，也不会与其产生直接关联。另外，我近期将会开源一个使用了 MultiType，并在 MultiType 之外实现了 LoadMoreDelegate 的客户端源代码，到时可以看看，这事完全不应该 MultiType 去掺手，毕竟它叫 MultiType 而不是 XXAdapter.

**Comment by drakeet** [comment]
另外我看你在邮件中还谈及了对 setItems 方法的不解，这个方法是在 v2.4.0 之后才提高的，是经过大量讨论与分析为了解决 RecyclerView 多并发操作更新出现异常，而提供的原子操作方法。至于让 CPU 做一次好比 1+1 一样简单的计算，这种性能问题是微乎其微的。如果你不了解为什么有必要提供一个 setItems 方法，可以无视它，因为 2.4.0 之前一直没有这个方法，等到发现 RV 数组越界异常或同步异常时，再来思考这个问题。

**Comment by woniu0936** [comment]
大赞！！！期待你的客户端开源，非常非常感谢大神的解惑！

**Comment by drakeet** [comment]
:P 不客气，我不是大神^ ^

**Comment by yushilong** [comment]
你好，LoadMoreDelegate项目还没开源吗
