### ISSUE TITLE
请问异步数据如何控制位置？

### ISSUE THREAD

**Issue by ssyijiu** [drakeet/MultiType#71]
你好，drakeet。
我的数据是网络获取的，在一个接口获取第一个数据之后 items.add() ,
在另一个接口获取第二个数据后也 items.add()，而网络请求是异步的，
这时会出现这两个数据在界面上显示位置错乱，在不考虑网络请求嵌套的情况下，
有没有什么好的解决办法。
我现在是这样做的，网络请求之前，先 items.add(index,data) 这两个类型数据的默认值来占位，
请求成功后先 items.remove(index) 再 items.add(index, data)，请求失败后 直接items.remove(index),
但是这样又会带来其他的问题。
请问你有什么好的解决方案吗？

**Comment by drakeet** [comment]
你的问题不属于 MultiType 的范畴，不应该在这个地方讨论。但我可以简单告诉你，你可以使用 RxJava 的 `zip` 操作符，或者 JDK 自带的 `CountDownLatch` 来实现。

**Comment by ssyijiu** [comment]
谢谢。
