### ISSUE TITLE
有没有支持ListView的多列表Adapter解决方案

### ISSUE THREAD

**Issue by jarlen** [drakeet/MultiType#74]
Dear Big God:

Can it support Adapter about ListView ?

**Comment by drakeet** [comment]
No, sorry, you are drunk.
![](https://camo.githubusercontent.com/bd9052cb8a5713d0ff354dfb8ab52dacdfd057c4/687474703a2f2f7777342e73696e61696d672e636e2f6c617267652f3565396138316462677731657539306d30387638366a323064773039613379752e6a7067)
