### ISSUE TITLE
MultiType 3.0

### ISSUE THREAD

**Issue by drakeet** [drakeet/MultiType#75]
- [x] Support one type to different(many) `ItemViewBinder`s in one `RecyclerView`
- [x] Rename the `ItemViewProvider` to `ItemViewBinder`(done in v2.5.0)
- [x] Remove all the `@Deprecated` classes/methods
- [x] Remove the golbal type pool `GlobalMultiTypePool`
- [x] Retrofit the constructors of `MultiTypeAdapter`
- [x] Fix some unchecked
- [x] Rename `TypePool#getContents()` to `getClasses()` (#109) 
- [x] Update and supply full docs

**Comment by drakeet** [comment]
We have made a breakthrough theoretical progress about the one2many.

**Comment by drakeet** [comment]
v2.x version will continue to update and maintain, so v3.x will give up part of the compatibility.

**Comment by woniu0936** [comment]
在使用的过程中，当items里面的bean类型太多的时候，动态的删除某一个item会比较麻烦，3.x能改进一下这方面吗？

**Comment by drakeet** [comment]
@woniu0936 这应该是和 position 绑定的，删除怎么会很麻烦呢 🤔 . 暂时没有这方面的计划。如果有什么想法，欢迎提出建设性建议(issue)和欢迎 PR.

**Comment by jk2K** [comment]
remove onFlattenClass

flatten class is not necessary for MultiType
MessageContent class should be added to items, not Message

**Comment by drakeet** [comment]
@jk2K MessageContent is just belong to TimeMachine. And we will remove all the @Deprecated classes/methods include the onFlatten methods of our adapter.

**Comment by drakeet** [comment]
BTW, to TimeMachine, it's easy to only sent message contents to the pool and providers, but we didn't do this actually,  we don't do this for no reason. 
All in all, what we used to do was a good design.

**Comment by beanu** [comment]
why remove GlobalMultiTypePool?  What is the alternative？

**Comment by drakeet** [comment]
@beanu GlobalMultiTypePool is evil, variable, and not intuitive.

**Comment by drakeet** [comment]
Maybe we could rename the ItemProvider to ItemBinder on 3.0

**Comment by cxMax** [comment]
what time we can meet the whole new MultiType 3.0 ? 
it's a long time for me to look forward version 3.0

**Comment by drakeet** [comment]
@cxMax I am very busy recently and expect to start in mid April.

**Comment by cxMax** [comment]
ok,no problem.
recently i meet a problem , in a complicate page which use a recyclerview and contains multi type item view.  it may has more than 40 categories.
so I just wanna to find a neat way to simplify generate code.

**Comment by drakeet** [comment]
Supported one type to many binders #106

**Comment by autofocus** [comment]
I use your library and  the class extends ItemViewProvider be named ItemViewTemplate

**Comment by drakeet** [comment]
@autofocus I don't understand what you said.

**Comment by drakeet** [comment]
Wiki has been updated with 3.0.
