### ISSUE TITLE
焦点事件问题

### ISSUE THREAD

**Issue by cheng1992zhen** [drakeet/MultiType#82]
当我的Item展示的是一张大图铺满了整个屏幕会导致我的列表无法刷新,焦点全被Item 占用,我使用的是 [BGARefreshLayout刷新和加载更多.](https://github.com/bingoogolapple/BGARefreshLayout-Android)

**Comment by drakeet** [comment]
这不是 MultiType 的问题和范畴，就是说你换成普通 RV adapter 同样会有这样的问题，请向 BGA 发起 issue. 

另外，如果你想集成下拉刷新和加载更多，可以参考我开源的 rebase-android，在 rebase-android 里开源了我写的下拉刷新或加载更多方案，完全解耦的 SwipeRefreshDelegate 和 LoadMoreDelegate: https://github.com/drakeet/rebase-android/blob/master/app/src/main/java/com/drakeet/rebase/fragment/ListBaseFragment.java#L49-L50

**Comment by cheng1992zhen** [comment]
好的,确实不是MultiType 的问题,已经解决了,谢谢你的解答.
