### ISSUE TITLE
why make items private

### ISSUE THREAD

**Issue by asker517** [drakeet/MultiType#83]
why in latest version make field `items` private ? it's not convenient for subclass use i think.

**Comment by drakeet** [comment]
We have provided setItems() and getItems(), so the filed items is better to be private.

**Comment by asker517** [comment]
I just not found `getItems()` in `MultiTypeAdapter` ...is it in other class ? version 2.4.2

**Comment by drakeet** [comment]
Sorry, at present, there is no such method, this is a bug, thank you for your reminder.

**Comment by asker517** [comment]
😄 plan to add the method in version 3.0?

**Comment by drakeet** [comment]
@asker517 I will create a patch for 2.4.2 and update to 2.4.3.

**Comment by asker517** [comment]
@drakeet OK,thanks 👍
