### ISSUE TITLE
请问在使用多种布局的时候，最底层的一个Provider是一个瀑布流的样式，加载更多之后，布局会留有空白

### ISSUE THREAD

**Issue by i91h1r** [drakeet/MultiType#85]
大神，这个要怎么解决额。在加载更多回调的方法中
`
    @Override public void loadMoreStepList(HomeBestPopStepResponse homeBestPopStepResponse) {

        bgaRefreshLayout.endLoadingMore();

        item.add(homeBestPopStepResponse);

        multiTypeAdapter.notifyDataSetChanged();

    }
`
这样源数据和新数据之间布局会留有空白的情况

**Comment by i91h1r** [comment]
@drakeet  求大神指点下额

**Comment by drakeet** [comment]
对不起，我没能明白你的需求和状况，请补充相关材料和描述。

**Comment by i91h1r** [comment]
@drakeet  首页会有banner，瀑布流。瀑布流在最下面的时候，加载更多数据，新的数据添加到items里面，然后原来的瀑布流布局会和新的之间留有空白位置

**Comment by drakeet** [comment]
@hyr0318 哦，我大致明白了，你 load more 加载的数据是瀑布流数据，同时，瀑布流是一个 item？这样的话，你应该把 more 数据交给瀑布流 item，而不是交给 `MultiTypeAdapter` 层次，若是这样会导致 new 一个瀑布流，变成两个瀑布流 items，它们当然是隔离的，末尾可能有空位。

**Comment by drakeet** [comment]
另外，如果你在 `RecyclerView` 里嵌套一个 **垂直**瀑布流 `RecyclerView`，这是不好的做法，一般会导致内嵌 `RecyclerView` 完全展开，失去复用性，若是瀑布流很大，可能导致 OOM.

**Comment by i91h1r** [comment]
@drakeet  嗯，我试过将新的数据交给瀑布流的adapter。debug上拉加载更多之后，adapte里面的list 会添加新的数据，但是界面 不会显示出来 新的数据

**Comment by drakeet** [comment]
对于瀑布流 + headers 这种需求，建议使用上下线性两个 `RecyclerView`s + `CoordinatorLayout`，这是性能友好型的实现方式，但对于 `CoordinatorLayout` 你可能需要关注下其设备版本兼容性。

**Comment by drakeet** [comment]
最近若是有时间，我可以写一个关于此的示例。Android 的 `StaggeredGridLayoutManager` 并非继承  `GridLayoutManager`，因此它没有类似于 `GridLayoutManager` 的 `setSpanSizeLookup` 方法，因此并不太适合包含多种不同宽度的子类型。

**Comment by drakeet** [comment]
@hyr0318 ：
> 我试过将新的数据交给瀑布流的adapter。debug上拉加载更多之后，adapte里面的list 会添加新的数据，但是界面 不会显示出来 新的数据

我不清楚你代码怎么写的，但大致可以猜到，你可能没有刷新嵌套的 瀑布流 item，或者它没有重新进行自我测量，因此末尾的 child views 显示不出来，你可以试试调用内嵌 RV 的 `requestLayout()` 方法试试。（当然了，上面说了，垂直嵌套垂直 这么做是不推荐的。

**Comment by i91h1r** [comment]
@drakeet 如果把瀑布流的布局单独出一个recycleview，那么和另外一个recycleview 一起在加上下拉刷新的控件之后滑动会变得非常卡。

**Comment by i91h1r** [comment]
@drakeet   大神，突然发现这样的问题，多种类型的布局，比如个是banner ，传到provider里面是一个；list，第二个是一个竖直的列表，传到provider里面去是list中的每一条数据，在手机上能正常显示，在模拟器上竖值的列表会显示不全或者有时候不显示，这个是什么原因额。

**Comment by drakeet** [comment]
这是 RecyclerView 的问题，RecyclerView 若是采用 wrap content 有自动测量机制，但不知道其兼容性如何。另外，我不知道你代码是怎么写的，因此无法断言你的问题原因。

**Comment by i91h1r** [comment]
大神，假如有一个评论列表，添加新的评论之后，要刷新这个列表，之前都是用items 添加进去的，重新获取数据之后，就会重复出现上一次的布局，这个谣怎么实现比较好额。 @drakeet

**Comment by drakeet** [comment]
@hyr0318 你的语言表达令我无法理解。

**Comment by i91h1r** [comment]
@drakeet  好尴尬。。。就是重新获取数据刷新列表时候，会重新往item中添加布局，导致 会有重复的布局出现，不知道有没有说清楚额 - -。

**Comment by i91h1r** [comment]
`
        Category category = new Category("全部评论", stepCommentRespnse.getAll_count());

        List<StepCommentResponse.ItemsBean> items = stepCommentRespnse.getItems();

        tempList.add(category);

        for (StepCommentResponse.ItemsBean itemsBean : items) {

            tempList.add(itemsBean);
        }

        multiTypeAdapter.notifyDataSetChanged();`    刷新数据 重新请求获取数据之后 会走这里，然后布局就会重复出现 ，就是刷新数据 要怎么处理比较好额

**Comment by drakeet** [comment]
@hyr0318 你只要调用 `items.clear()` 之后再重新 `items.addAll(list)` 即可。但考虑到多并发之下的安全性，建议使用原子操作：调用 `adapter.setItems(list)` 并传递一个全新 items list 对象。

另外，请不要再这里讨论与主题无关的内容，请尽量使用英文进行提问。

**Comment by drakeet** [comment]
@hyr0318 关于如何刷新数据，你原来使用传统 RecyclerView 如何刷新就一样如何刷新，MultiType 只是很薄的一层，它只负责类型分发，并不会去管你的数据应该如何操作。

另外，如果你实在不理解，你可以参考我开源的 [rebase-android](https://github.com/drakeet/rebase-android) 项目，这个项目使用了 MultiType，具有下拉刷新、加载更多功能，代码十分清晰可读，或许对你有帮助。

**Comment by i91h1r** [comment]
@drakeet  原来 就直接adapter 重新给数据源就可以啦。但是用大神的这个，clear 之后，会吧之前的布局也给清掉，只需要刷新部分布局的数据 不知道怎么处理比较好额 - 。-

**Comment by drakeet** [comment]
并不会把之前的布局清掉：
```java
items.clear();
items.addAll(newList);
adapter.notifyDataSetChanged();
```

**Comment by drakeet** [comment]
你的需求一直很不明确，语言表达也很不清晰，错别字很多也不改，代码贴出来之后也不自觉先 preview 看看格式有没有问题，并且鉴于我已经说得很清楚了，MultiType 只是很薄的一层，它只负责类型分发，其余一概不管一概保持与原生 Adapter 一样，所以你在讨论的内容几乎都不属于 MultiType 的范畴，为了避免更多订阅了本项目的人被打扰，关闭了这个 issue，如果还有问题，请考虑清楚后，描述清楚，开启新的 issue 或者给我写邮件，谢谢！
