### ISSUE TITLE
可以在ItemViewProvider中加入onViewRecycled吗

### ISSUE THREAD

**Issue by sanniou** [drakeet/MultiType#86]
现有方法要在回收时进行操作似乎还是得回到MultiTypeAdapter上，很不直观

**Comment by drakeet** [comment]
感谢反馈，值得考虑 🤔

**Comment by drakeet** [comment]
该方法已经提供。

**Comment by drakeet** [comment]
https://github.com/drakeet/MultiType/pull/103
If you need to do something on `onViewRecycled`, you'd better
inherit MultiTypeAdapter do it.
