### ISSUE TITLE
adapter.notifyDataSetChanged()遇见的问题

### ISSUE THREAD

**Issue by wuyinlei** [drakeet/MultiType#88]
您好大神，问下哈，就是我使用这个控件，但是在加载更多的时候 
```
  //加载更多的数据
                        Items objects = loadMoreData();
                        //原始数据填充
                        originItems.addAll(objects);
                        adapter.notifyDataSetChanged();

                        Toast.makeText(mContext, "加载更多完成", Toast.LENGTH_SHORT).show();
```
这个时候数据加载也是正确的，但是刷新UI的时候，会跳动到最后一条或者在往上跳动,不是那种很平滑的(就是我要监听滑动到底部，加载更多，那么这个时候如果很自然的加载应该是加载完成之后如果不滑动，显示的还是当前界面，但是可以上滑动)  现在会往上跳动一下，请问这个怎么解决还是我那个地方使用出错。

**Comment by drakeet** [comment]
MultiType 只是很薄的一层，不会影响到你的 UI 焦点和滑动，你可以自行阅读其源码获得深层了解。对于你的问题，从你的代码片段和描述中，我无法得知你具体问题代码是怎么回事。

另外，由于越来越多人使用中文创建 issue，我想说一下，建议改为英文描述，能够让更多国外的朋友关注和了解相关问题。

**Comment by drakeet** [comment]
对于 LoadMore，你可以参考我开源的 rebase-android 项目：https://github.com/drakeet/rebase-android
rebase-android 使用了 MultiType 加载列表，并且由我创建了一非常易用、完善的 LoadMore 机制：
https://github.com/drakeet/rebase-android/blob/master/app/src/main/java/com/drakeet/rebase/fragment/ListBaseFragment.java

**Comment by wuyinlei** [comment]
好的，我估计也是 ，因为之前我也用过，感觉也不会是这个框架的问题，我在看看的，谢谢回复哈
